export interface LengkapiSukuKataBelakangDataItem {
  id: string;
  display: string;
  answer: string;
  choices: string[];
  image: string;
}

export const lengkapiSukuKataDepanData: LengkapiSukuKataBelakangDataItem[] = [
  { id: 'sapu', display: '__-pu', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🧹' },
  { id: 'buku', display: '__-ku', answer: 'bu', choices: ['bu', 'ba', 'bo'], image: '📖' },
  { id: 'topi', display: '__-pi', answer: 'to', choices: ['to', 'ta', 'ti'], image: '🎩' },
  { id: 'roda', display: '__-da', answer: 'ro', choices: ['ro', 'ra', 'ri'], image: '🛞' },
  { id: 'baju', display: '__-ju', answer: 'ba', choices: ['ba', 'bi', 'be'], image: '👕' },
  { id: 'mata', display: '__-ta', answer: 'ma', choices: ['ma', 'mi', 'me'], image: '👁️' },
  { id: 'kaki', display: '__-ki', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🦵' },
  { id: 'nasi', display: '__-si', answer: 'na', choices: ['na', 'ni', 'ne'], image: '🍚' },
  { id: 'gigi', display: '__-gi', answer: 'gi', choices: ['gi', 'ga', 'ge'], image: '🦷' },
  { id: 'dadu', display: '__-du', answer: 'da', choices: ['da', 'di', 'de'], image: '🎲' },
  { id: 'mama', display: '__-ma', answer: 'ma', choices: ['ma', 'mi', 'me'], image: '👩' },
  { id: 'papa', display: '__-pa', answer: 'pa', choices: ['pa', 'pi', 'pe'], image: '👨' },
  { id: 'susu', display: '__-su', answer: 'su', choices: ['su', 'si', 'se'], image: '🥛' },
  { id: 'kuku', display: '__-ku', answer: 'ku', choices: ['ku', 'ka', 'ke'], image: '💅' },
  { id: 'nada', display: '__-da', answer: 'na', choices: ['na', 'la', 'ba'], image: '🎵' },
  { id: 'kereta', display: '__-re-ta', answer: 'ke', choices: ['ka', 'ki', 'ke'], image: '🚂' },
  { id: 'pesawat', display: '__-sa-wat', answer: 'pe', choices: ['pe', 'pa', 'pi'], image: '✈️' },
  { id: 'kopi', display: '__-pi', answer: 'ko', choices: ['ko', 'ka', 'ki'], image: '☕' },
  { id: 'air', display: '__-ir', answer: 'a', choices: ['a', 'i', 'e'], image: '💧' },
  { id: 'lari', display: '__-ri', answer: 'la', choices: ['la', 'li', 'le'], image: '🏃' },
  { id: 'babi', display: '__-bi', answer: 'ba', choices: ['ba', 'be', 'bo'], image: '🐖' },
  { id: 'roket', display: '__-ket', answer: 'ro', choices: ['ra', 'ri', 'ro'], image: '🚀' },
  { id: 'kaktus', display: '__-tus', answer: 'kak', choices: ['lak', 'kak', 'dak'], image: '🌵' },
  { id: 'foto', display: '__-to', answer: 'fo', choices: ['fo', 'fa', 'fi'], image: '📷' },
  { id: 'guru', display: '__-ru', answer: 'gu', choices: ['gu', 'ga', 'ge'], image: '👩‍🏫' },
  { id: 'hati', display: '__-ti', answer: 'ha', choices: ['ha', 'hi', 'he'], image: '❤️' },
  { id: 'ikan', display: '__-kan', answer: 'i', choices: ['i', 'e', 'a'], image: '🐟' },
  { id: 'jari', display: '__-ri', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '👆' },
  { id: 'kota', display: '__-ta', answer: 'ko', choices: ['ko', 'ka', 'ki'], image: '🏙️' },
  { id: 'cincin', display: '__-cin', answer: 'cin', choices: ['cin', 'lin', 'sin'], image: '💍' },
  { id: 'palu', display: '__-lu', answer: 'pa', choices: ['pe', 'pa', 'pi'], image: '🔨' },
  { id: 'teleskop', display: '__-le-skop', answer: 'te', choices: ['ta', 'te', 'ne'], image: '🔭' },
  { id: 'celana', display: '__-la-na', answer: 'ce', choices: ['ca', 'ci', 'ce'], image: '👖' },
  { id: 'rusa', display: '__-sa', answer: 'ru', choices: ['ru', 'ra', 'ri'], image: '🦌' },
  { id: 'sapi', display: '__-pi', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🐄' },
  { id: 'tangan', display: '__-gan', answer: 'tan', choices: ['tan', 'tin', 'ten'], image: '✋' }, // tang-ga
  { id: 'ular', display: '__-lar', answer: 'u', choices: ['u', 'o', 'a'], image: '🐍' },
  { id: 'bunga', display: '__-nga', answer: 'bu', choices: ['ba', 'bu', 'be'], image: '🌸' },
  { id: 'bola', display: '__-la', answer: 'bo', choices: ['bo', 'ba', 'bi'], image: '⚽' },
  { id: 'cinta', display: '__-ta', answer: 'cin', choices: ['cin', 'can', 'cen'], image: '💕' },
  { id: 'dapur', display: '__-pur', answer: 'da', choices: ['da', 'di', 'de'], image: '🍳' },
  { id: 'brokoli', display: '__-ko-li', answer: 'bro', choices: ['bre', 'bro', 'bri'], image: '🥦' },
  { id: 'madu', display: '__-du', answer: 'ma', choices: ['mu', 'ma', 'mi'], image: '🍯' },
  { id: 'hujan', display: '__-jan', answer: 'hu', choices: ['hu', 'ha', 'hi'], image: '🌧️' },
  { id: 'jaket', display: '__-ket', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '🧥' },
  { id: 'kamar', display: '__-mar', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🛏️' },
  { id: 'laptop', display: '__-top', answer: 'lap', choices: ['lap', 'lip', 'lep'], image: '💻' },
  { id: 'mobil', display: '__-bil', answer: 'mo', choices: ['mo', 'ma', 'mi'], image: '🚗' },
  { id: 'matahari', display: '__-ta-ha-ri', answer: 'ma', choices: ['mo', 'ma', 'mi'], image: '🌞' },
  { id: 'pantai', display: '__-tai', answer: 'pan', choices: ['pan', 'pin', 'pen'], image: '🏖️' },
  { id: 'rumah', display: '__-mah', answer: 'ru', choices: ['ru', 'ra', 'ri'], image: '🏠' },
  { id: 'sepatu', display: '__-pa-tu', answer: 'se', choices: ['se', 'sa', 'si'], image: '👟' },
  { id: 'uang', display: '__-ang', answer: 'u', choices: ['u', 'o', 'a'], image: '💰' },
  { id: 'jamur', display: '__-mur', answer: 'ja', choices: ['ji', 'ja', 'je'], image: '🍄' },
  { id: 'payung', display: '__-yung', answer: 'pa', choices: ['pa', 'po', 'pe'], image: '☂️' }, 
  { id: 'telepon', display: '__-le-pon', answer: 'te', choices: ['te', 'ta', 'ti'], image: '📞' },
  { id: 'kucing', display: '__-cing', answer: 'ku', choices: ['ku', 'ka', 'ki'], image: '🐱' },
  { id: 'mangga', display: '__-ga', answer: 'mang', choices: ['mang', 'man', 'meng'], image: '🥭' }, // mang-ga
  { id: 'pisang', display: '__-sang', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🍌' },
  { id: 'kelapa', display: '__-la-pa', answer: 'ke', choices: ['ke', 'ka', 'ki'], image: '🥥' },
  { id: 'jeruk', display: '__-ruk', answer: 'je', choices: ['je', 'ja', 'ji'], image: '🍊' },
  { id: 'wortel', display: '__-tel', answer: 'wor', choices: ['wor', 'war', 'wir'], image: '🥕' }, // wor-tel
  { id: 'ayam', display: '__-yam', answer: 'a', choices: ['a', 'i', 'e'], image: '🐔' },
  { id: 'telur', display: '__-lur', answer: 'te', choices: ['te', 'ta', 'ti'], image: '🥚' },
  { id: 'itik', display: '__-tik', answer: 'i', choices: ['i', 'e', 'a'], image: '🐥' },
  { id: 'kambing', display: '__-bing', answer: 'kam', choices: ['kam', 'kem', 'kim'], image: '🐐' },
  { id: 'boneka', display: '__-ne-ka', answer: 'bo', choices: ['bo', 'ba', 'bi'], image: '🧸' },
  { id: 'naga', display: '__-ga', answer: 'na', choices: ['na', 'ni', 'ne'], image: '🐉' },
  { id: 'kunci', display: '__-ci', answer: 'kun', choices: ['kun', 'kan', 'kin'], image: '🔑' },
  { id: 'lemari', display: '__-ma-ri', answer: 'le', choices: ['le', 'la', 'li'], image: '🗄️' },
  { id: 'kasur', display: '__-sur', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🛏️' },
  { id: 'salju', display: '__-ju', answer: 'sal', choices: ['bal', 'nal', 'sal'], image: '❄️' },
  { id: 'cermin', display: '__-min', answer: 'cer', choices: ['cer', 'car', 'cir'], image: '🪞' },
  { id: 'lampu', display: '__-pu', answer: 'lam', choices: ['lam', 'lem', 'lim'], image: '💡' },
  { id: 'katak', display: '__-tak', answer: 'ka', choices: ['ki', 'ka', 'ke'], image: '🐸' },
  { id: 'radio', display: '__-dio', answer: 'ra', choices: ['ra', 'ri', 're'], image: '📻' },
  { id: 'gajah', display: '__-jah', answer: 'ga', choices: ['ja', 'la', 'ga'], image: '🐘' },
  { id: 'wajan', display: '__-jan', answer: 'wa', choices: ['wa', 'wi', 'we'], image: '🍳' },
  { id: 'piring', display: '__-ring', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🍽️' },
  { id: 'gelas', display: '__-las', answer: 'ge', choices: ['ge', 'ga', 'gi'], image: '🥤' },
  { id: 'sendok', display: '__-ndok', answer: 'sen', choices: ['sen', 'san', 'sin'], image: '🥄' },
  { id: 'sofa', display: '__-fa', answer: 'so', choices: ['sa', 'so', 'si'], image: '🛋️' },
  { id: 'pisau', display: '__-sau', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🔪' },
  { id: 'ember', display: '__-ber', answer: 'em', choices: ['em', 'am', 'im'], image: '🪣' },
  { id: 'keju', display: '__-ju', answer: 'ke', choices: ['ka', 'ki', 'ke'], image: '🧀' },
  { id: 'sabun', display: '__-bun', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🧼' },
  { id: 'sikat', display: '__-kat', answer: 'si', choices: ['si', 'sa', 'se'], image: '🪥' },
  { id: 'tas', display: '__-as', answer: 't', choices: ['t', 'b', 'p'], image: '🎒' },
  { id: 'handuk', display: '__-duk', answer: 'han', choices: ['han', 'hen', 'hin'], image: '🛁' },
  { id: 'tisu', display: '__-su', answer: 'ti', choices: ['ti', 'ta', 'te'], image: '🧻' },
  { id: 'roti', display: '__-ti', answer: 'ro', choices: ['ro', 'ra', 'ri'], image: '🍞' },
  { id: 'kue', display: '__-e', answer: 'ku', choices: ['ku', 'ke', 'ki'], image: '🍰' },
  { id: 'apel', display: '__-pel', answer: 'a', choices: ['u', 'a', 'i'], image: '🍎' },
  { id: 'kupu', display: '__-pu', answer: 'ku', choices: ['ku', 'ka', 'ki'], image: '🦋' },
  { id: 'kipas', display: '__-pas', answer: 'ki', choices: ['ku', 'ka', 'ki'], image: '🪭' },
  { id: 'burung', display: '__-rung', answer: 'bu', choices: ['bu', 'ba', 'bi'], image: '🐦' },
  { id: 'cangkir', display: '__-kir', answer: 'cang', choices: ['cang', 'cing', 'ceng'], image: '☕' },
  { id: 'mainan', display: '__-nan', answer: 'mai', choices: ['mai', 'mi', 'me'], image: '🧸' },
  { id: 'piano', display: '__-a-no', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🎹' },
  { id: 'gitar', display: '__-tar', answer: 'gi', choices: ['ga', 'gi', 'ge'], image: '🎸' },
  { id: 'laut', display: '__-ut', answer: 'la', choices: ['la', 'li', 'le'], image: '🌊' },
  { id: 'kepala', display: '__-pa-la', answer: 'ke', choices: ['ke', 'ka', 'ki'], image: '🙂' },
  { id: 'pintu', display: '__-tu', answer: 'pin', choices: ['pin', 'pan', 'pen'], image: '🚪' },
  { id: 'rambut', display: '__-but', answer: 'ram', choices: ['ram', 'rem', 'rim'], image: '💇' },
  { id: 'tangga', display: '__-ga', answer: 'tang', choices: ['tang', 'ting', 'teng'], image: '🪜' },
  { id: 'angin', display: '__-ngin', answer: 'a', choices: ['a', 'i', 'e'], image: '💨' },
  { id: 'kertas', display: '__-tas', answer: 'ker', choices: ['ker', 'kar', 'kir'], image: '📄' },
  { id: 'pensil', display: '__-sil', answer: 'pen', choices: ['pan', 'pen', 'pun'], image: '✏️' }
];
