export interface LengkapiSukuKataBelakangDataItem {
  id: string;
  display: string;
  answer: string;
  choices: string[];
  image: string;
}

export const lengkapiSukuKataDepanData: LengkapiSukuKataBelakangDataItem[] = [
  { id: 'sapu', display: '__-pu', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🧹' },
  { id: 'buka', display: '__-ka', answer: 'bu', choices: ['bu', 'ba', 'bo'], image: '📖' },
  { id: 'topi', display: '__-pi', answer: 'to', choices: ['to', 'ta', 'ti'], image: '🎩' },
  { id: 'roda', display: '__-da', answer: 'ro', choices: ['ro', 'ra', 'ri'], image: '🛞' },
  { id: 'baju', display: '__-ju', answer: 'ba', choices: ['ba', 'bi', 'be'], image: '👕' },
  { id: 'mata', display: '__-ta', answer: 'ma', choices: ['ma', 'mi', 'me'], image: '👁️' },
  { id: 'kaki', display: '__-ki', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🦵' },
  { id: 'nasi', display: '__-si', answer: 'na', choices: ['na', 'ni', 'ne'], image: '🍚' },
  { id: 'gigi', display: '__-gi', answer: 'gi', choices: ['gi', 'ga', 'ge'], image: '🦷' },
  { id: 'dada', display: '__-da', answer: 'da', choices: ['da', 'di', 'de'], image: '🫁' },
  { id: 'mama', display: '__-ma', answer: 'ma', choices: ['ma', 'mi', 'me'], image: '👩' },
  { id: 'papa', display: '__-pa', answer: 'pa', choices: ['pa', 'pi', 'pe'], image: '👨' },
  { id: 'susu', display: '__-su', answer: 'su', choices: ['su', 'si', 'se'], image: '🥛' },
  { id: 'kuku', display: '__-ku', answer: 'ku', choices: ['ku', 'ka', 'ke'], image: '💅' },
  { id: 'lala', display: '__-la', answer: 'la', choices: ['la', 'li', 'le'], image: '🎵' },
  { id: 'tahu', display: '__-hu', answer: 'ta', choices: ['ta', 'ti', 'te'], image: '🧈' },
  { id: 'soto', display: '__-to', answer: 'so', choices: ['so', 'sa', 'si'], image: '🍲' },
  { id: 'kopi', display: '__-pi', answer: 'ko', choices: ['ko', 'ka', 'ki'], image: '☕' },
  { id: 'air', display: '__-ir', answer: 'a', choices: ['a', 'i', 'e'], image: '💧' },
  { id: 'lari', display: '__-ri', answer: 'la', choices: ['la', 'li', 'le'], image: '🏃' },
  { id: 'babi', display: '__-bi', answer: 'ba', choices: ['ba', 'be', 'bo'], image: '🐖' },
  { id: 'cari', display: '__-ri', answer: 'ca', choices: ['ca', 'ci', 'ce'], image: '🔍' },
  { id: 'duri', display: '__-ri', answer: 'du', choices: ['du', 'di', 'de'], image: '🌵' },
  { id: 'foto', display: '__-to', answer: 'fo', choices: ['fo', 'fa', 'fi'], image: '📷' },
  { id: 'guru', display: '__-ru', answer: 'gu', choices: ['gu', 'ga', 'ge'], image: '👩‍🏫' },
  { id: 'hati', display: '__-ti', answer: 'ha', choices: ['ha', 'hi', 'he'], image: '❤️' },
  { id: 'ikan', display: '__-kan', answer: 'i', choices: ['i', 'e', 'a'], image: '🐟' },
  { id: 'jari', display: '__-ri', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '👆' },
  { id: 'kota', display: '__-ta', answer: 'ko', choices: ['ko', 'ka', 'ki'], image: '🏙️' },
  { id: 'lucu', display: '__-cu', answer: 'lu', choices: ['lu', 'la', 'le'], image: '😄' },
  { id: 'meja', display: '__-ja', answer: 'me', choices: ['me', 'ma', 'mi'], image: '🪑' },
  { id: 'nada', display: '__-da', answer: 'na', choices: ['na', 'ni', 'ne'], image: '🎵' },
  { id: 'pagi', display: '__-gi', answer: 'pa', choices: ['pa', 'pi', 'pe'], image: '🌅' },
  { id: 'rusa', display: '__-sa', answer: 'ru', choices: ['ru', 'ra', 'ri'], image: '🦌' },
  { id: 'sapi', display: '__-pi', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🐄' },
  { id: 'tangan', display: '__-gan', answer: 'tan', choices: ['tan', 'tin', 'ten'], image: '✋' }, // tang-ga
  { id: 'ular', display: '__-lar', answer: 'u', choices: ['u', 'o', 'a'], image: '🐍' },
  { id: 'wangi', display: '__-ngi', answer: 'wa', choices: ['wa', 'wi', 'we'], image: '🌸' },
  { id: 'bola', display: '__-la', answer: 'bo', choices: ['bo', 'ba', 'bi'], image: '⚽' },
  { id: 'cinta', display: '__-ta', answer: 'cin', choices: ['cin', 'can', 'cen'], image: '💕' },
  { id: 'dapur', display: '__-pur', answer: 'da', choices: ['da', 'di', 'de'], image: '🍳' },
  { id: 'emas', display: '__-mas', answer: 'e', choices: ['e', 'a', 'i'], image: '🪙' },
  { id: 'gula', display: '__-la', answer: 'gu', choices: ['gu', 'ga', 'gi'], image: '🍯' },
  { id: 'hujan', display: '__-jan', answer: 'hu', choices: ['hu', 'ha', 'hi'], image: '🌧️' },
  { id: 'jaket', display: '__-ket', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '🧥' },
  { id: 'kamar', display: '__-mar', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🛏️' },
  { id: 'laptop', display: '__-top', answer: 'lap', choices: ['lap', 'lip', 'lep'], image: '💻' },
  { id: 'mobil', display: '__-bil', answer: 'mo', choices: ['mo', 'ma', 'mi'], image: '🚗' },
  { id: 'novel', display: '__-vel', answer: 'no', choices: ['no', 'na', 'ni'], image: '📚' },
  { id: 'pantai', display: '__-tai', answer: 'pan', choices: ['pan', 'pin', 'pen'], image: '🏖️' },
  { id: 'rumah', display: '__-mah', answer: 'ru', choices: ['ru', 'ra', 'ri'], image: '🏠' },
  { id: 'sepatu', display: '__-pa-tu', answer: 'se', choices: ['se', 'sa', 'si'], image: '👟' },
  { id: 'uang', display: '__-ang', answer: 'u', choices: ['u', 'o', 'a'], image: '💰' },
  { id: 'vitamin', display: '__-ta-min', answer: 'vi', choices: ['vi', 'va', 've'], image: '💊' },
  { id: 'warna', display: '__-na', answer: 'war', choices: ['war', 'wan', 'wer'], image: '🎨' }, // war-na
  { id: 'telepon', display: '__-le-pon', answer: 'te', choices: ['te', 'ta', 'ti'], image: '📞' },
  { id: 'kucing', display: '__-cing', answer: 'ku', choices: ['ku', 'ka', 'ki'], image: '🐱' },
  { id: 'mangga', display: '__-ga', answer: 'mang', choices: ['mang', 'man', 'meng'], image: '🥭' }, // mang-ga
  { id: 'pisang', display: '__-sang', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🍌' },
  { id: 'kelapa', display: '__-la-pa', answer: 'ke', choices: ['ke', 'ka', 'ki'], image: '🥥' },
  { id: 'jeruk', display: '__-ruk', answer: 'je', choices: ['je', 'ja', 'ji'], image: '🍊' },
  { id: 'wortel', display: '__-tel', answer: 'wor', choices: ['wor', 'war', 'wir'], image: '🥕' }, // wor-tel
  { id: 'ayam', display: '__-yam', answer: 'a', choices: ['a', 'i', 'e'], image: '🐔' },
  { id: 'telur', display: '__-lur', answer: 'te', choices: ['te', 'ta', 'ti'], image: '🥚' },
  { id: 'itik', display: '__-tik', answer: 'i', choices: ['i', 'e', 'a'], image: '🦆' },
  { id: 'kambing', display: '__-bing', answer: 'kam', choices: ['kam', 'kem', 'kim'], image: '🐐' },
  { id: 'boneka', display: '__-ne-ka', answer: 'bo', choices: ['bo', 'ba', 'bi'], image: '🧸' },
  { id: 'balok', display: '__-lok', answer: 'ba', choices: ['ba', 'bi', 'be'], image: '🧱' },
  { id: 'kunci', display: '__-ci', answer: 'kun', choices: ['kun', 'kan', 'kin'], image: '🔑' },
  { id: 'lemari', display: '__-ma-ri', answer: 'le', choices: ['le', 'la', 'li'], image: '🗄️' },
  { id: 'kasur', display: '__-sur', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🛏️' },
  { id: 'bantal', display: '__-ntal', answer: 'ban', choices: ['ban', 'ben', 'bin'], image: '🛏️' },
  { id: 'cermin', display: '__-min', answer: 'cer', choices: ['cer', 'car', 'cir'], image: '🪞' },
  { id: 'lampu', display: '__-pu', answer: 'lam', choices: ['lam', 'lem', 'lim'], image: '💡' },
  { id: 'kipas', display: '__-pas', answer: 'ki', choices: ['ki', 'ka', 'ke'], image: '🌀' },
  { id: 'radio', display: '__-dio', answer: 'ra', choices: ['ra', 'ri', 're'], image: '📻' },
  { id: 'kompor', display: '__-por', answer: 'kom', choices: ['kom', 'kam', 'kem'], image: '🔥' },
  { id: 'wajan', display: '__-jan', answer: 'wa', choices: ['wa', 'wi', 'we'], image: '🍳' },
  { id: 'piring', display: '__-ring', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🍽️' },
  { id: 'gelas', display: '__-las', answer: 'ge', choices: ['ge', 'ga', 'gi'], image: '🥤' },
  { id: 'sendok', display: '__-ndok', answer: 'sen', choices: ['sen', 'san', 'sin'], image: '🥄' },
  { id: 'garpu', display: '__-rpu', answer: 'gar', choices: ['gar', 'ger', 'gir'], image: '🍴' },
  { id: 'pisau', display: '__-sau', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🔪' },
  { id: 'ember', display: '__-ber', answer: 'em', choices: ['em', 'am', 'im'], image: '🪣' },
  { id: 'kain', display: '__-in', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🧺' },
  { id: 'sabun', display: '__-bun', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🧼' },
  { id: 'sikat', display: '__-kat', answer: 'si', choices: ['si', 'sa', 'se'], image: '🪥' },
  { id: 'sampo', display: '__-po', answer: 'sam', choices: ['sam', 'sem', 'sim'], image: '🧴' },
  { id: 'handuk', display: '__-duk', answer: 'han', choices: ['han', 'hen', 'hin'], image: '🛁' },
  { id: 'tisu', display: '__-su', answer: 'ti', choices: ['ti', 'ta', 'te'], image: '🧻' },
  { id: 'roti', display: '__-ti', answer: 'ro', choices: ['ro', 'ra', 'ri'], image: '🍞' },
  { id: 'kue', display: '__-e', answer: 'ku', choices: ['ku', 'ke', 'ki'], image: '🍰' },
  { id: 'buah', display: '__-ah', answer: 'bu', choices: ['bu', 'ba', 'bi'], image: '🍎' },
  { id: 'kupu', display: '__-pu', answer: 'ku', choices: ['ku', 'ka', 'ki'], image: '🦋' },
  { id: 'bunga', display: '__-nga', answer: 'bu', choices: ['bu', 'ba', 'bi'], image: '🌸' },
  { id: 'burung', display: '__-rung', answer: 'bu', choices: ['bu', 'ba', 'bi'], image: '🐦' },
  { id: 'cangkir', display: '__-kir', answer: 'cang', choices: ['cang', 'cing', 'ceng'], image: '☕' },
  { id: 'mainan', display: '__-nan', answer: 'mai', choices: ['mai', 'mi', 'me'], image: '🧸' },
  { id: 'piano', display: '__-a-no', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🎹' },
  { id: 'jalan', display: '__-lan', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '🛤️' },
  { id: 'laut', display: '__-ut', answer: 'la', choices: ['la', 'li', 'le'], image: '🌊' },
  { id: 'kepala', display: '__-pa-la', answer: 'ke', choices: ['ke', 'ka', 'ki'], image: '🙂' },
  { id: 'pintu', display: '__-tu', answer: 'pin', choices: ['pin', 'pan', 'pen'], image: '🚪' },
  { id: 'rambut', display: '__-but', answer: 'ram', choices: ['ram', 'rem', 'rim'], image: '💇' },
  { id: 'tangga', display: '__-ga', answer: 'tang', choices: ['tang', 'ting', 'teng'], image: '🪜' },
  { id: 'angin', display: '__-ngin', answer: 'a', choices: ['a', 'i', 'e'], image: '💨' },
  { id: 'kertas', display: '__-tas', answer: 'ker', choices: ['ker', 'kar', 'kir'], image: '📄' },
  { id: 'zaitun', display: '__-tun', answer: 'zai', choices: ['zai', 'ze', 'zi'], image: '🫒' }
];
