export interface AwalKataDataItem {
  id: string;
  image: string;
  answer: string;
  choices: string[];
}

export const awalKataData: AwalKataDataItem[] = [
  { "id": "Mata", "image": "👁️", "answer": "m", "choices": ["m", "i", "u"] },
  { "id": "Hidung", "image": "👃", "answer": "h", "choices": ["h", "k", "n"] },
  { "id": "Mulut", "image": "👄", "answer": "m", "choices": ["m", "d", "k"] },
  { "id": "Telinga", "image": "👂", "answer": "t", "choices": ["t", "i", "u"] },
  { "id": "Tangan", "image": "✋", "answer": "t", "choices": ["t", "m", "g"] },
  { "id": "Kaki", "image": "🦵", "answer": "k", "choices": ["k", "a", "u"] },
  { "id": "Rambut", "image": "💇", "answer": "r", "choices": ["r", "d", "k"] },
  { "id": "Badak", "image": "🦏", "answer": "b", "choices": ["b", "d", "k"] },
  { "id": "Nyamuk", "image": "🦟", "answer": "n", "choices": ["n", "k", "g"] },
  { "id": "Lutut", "image": "🦵", "answer": "l", "choices": ["l", "d", "k"] },
  { "id": "Otot", "image": "💪", "answer": "o", "choices": ["u", "o", "i"] },
  { "id": "Jari", "image": "👆", "answer": "j", "choices": ["j", "a", "u"] },
  { "id": "Kuku", "image": "💅", "answer": "k", "choices": ["k", "o", "i"] },
  { "id": "Mawar", "image": "🌹", "answer": "m", "choices": ["m", "o", "i"] },
  { "id": "Bulan", "image": "🌙", "answer": "b", "choices": ["r", "l", "b"] },
  { "id": "Meteor", "image": "☄️", "answer": "m", "choices": ["r", "l", "t"] },
  { "id": "Tornado", "image": "🌪️", "answer": "t", "choices": ["o", "a", "u"] },
  { "id": "Petir", "image": "⚡", "answer": "p", "choices": ["s", "c", "r"] },
  { "id": "Bibir", "image": "👄", "answer": "b", "choices": ["r", "l", "n"] },
  { "id": "Gigi", "image": "🦷", "answer": "g", "choices": ["i", "a", "u"] },
  { "id": "Lidah", "image": "👅", "answer": "l", "choices": ["h", "k", "m"] },
  { "id": "Kiwi", "image": "🥝", "answer": "k", "choices": ["a", "i", "u"] },
  { "id": "Kursi", "image": "🪑", "answer": "k", "choices": ["i", "a", "u"] },
  { "id": "Sofa", "image": "🛋️", "answer": "s", "choices": ["a", "i", "u"] },
  { "id": "Pintu", "image": "🚪", "answer": "p", "choices": ["u", "o", "i"] },
  { "id": "Jendela", "image": "🪟", "answer": "j", "choices": ["a", "i", "u"] },
  { "id": "Lemari", "image": "🗄️", "answer": "l", "choices": ["i", "a", "u"] },
  { "id": "Kasur", "image": "🛏️", "answer": "k", "choices": ["r", "l", "n"] },
  { "id": "Toples", "image": "🫙", "answer": "t", "choices": ["l", "r", "s"] },
  { "id": "Cermin", "image": "🪞", "answer": "c", "choices": ["n", "m", "g"] },
  { "id": "Lampu", "image": "💡", "answer": "l", "choices": ["u", "o", "i"] },
  { "id": "Sumpit", "image": "🥢", "answer": "s", "choices": ["s", "c", "t"] },
  { "id": "TV", "image": "📺", "answer": "t", "choices": ["v", "f", "b"] },
  { "id": "Radio", "image": "📻", "answer": "r", "choices": ["o", "u", "i"] },
  { "id": "Api", "image": "🔥", "answer": "a", "choices": ["r", "i", "n"] },
  { "id": "Wajan", "image": "🍳", "answer": "w", "choices": ["n", "m", "g"] },
  { "id": "Piring", "image": "🍽️", "answer": "p", "choices": ["g", "k", "n"] },
  { "id": "Gelas", "image": "🥤", "answer": "g", "choices": ["s", "c", "t"] },
  { "id": "Sendok", "image": "🥄", "answer": "s", "choices": ["k", "g", "h"] },
  { "id": "Garpu", "image": "🍴", "answer": "g", "choices": ["u", "o", "i"] },
  { "id": "Pisau", "image": "🔪", "answer": "p", "choices": ["u", "o", "i"] },
  { "id": "Nasi", "image": "🍚", "answer": "n", "choices": ["i", "a", "u"] },
  { "id": "Air", "image": "💧", "answer": "a", "choices": ["a", "i", "u"] },
  { "id": "Susu", "image": "🥛", "answer": "s", "choices": ["s", "m", "b"] },
  { "id": "Roti", "image": "🍞", "answer": "r", "choices": ["r", "l", "k"] },
  { "id": "Kue", "image": "🍰", "answer": "k", "choices": ["k", "m", "b"] },
  { "id": "Buah", "image": "🍎", "answer": "b", "choices": ["b", "p", "m"] },
  { "id": "Mangga", "image": "🥭", "answer": "m", "choices": ["m", "b", "p"] },
  { "id": "Pisang", "image": "🍌", "answer": "p", "choices": ["p", "b", "m"] },
  { "id": "Kelapa", "image": "🥥", "answer": "k", "choices": ["k", "m", "g"] },
  { "id": "Jeruk", "image": "🍊", "answer": "j", "choices": ["j", "c", "g"] },
  { "id": "Wortel", "image": "🥕", "answer": "w", "choices": ["w", "k", "m"] },
  { "id": "Ayam", "image": "🐔", "answer": "a", "choices": ["a", "i", "u"] },
  { "id": "Ikan", "image": "🐟", "answer": "i", "choices": ["i", "a", "u"] },
  { "id": "Telur", "image": "🥚", "answer": "t", "choices": ["t", "d", "k"] },
  { "id": "Bunga", "image": "🌸", "answer": "b", "choices": ["b", "p", "m"] },
  { "id": "Pohon", "image": "🌳", "answer": "p", "choices": ["p", "b", "m"] },
  { "id": "Rumput", "image": "🌱", "answer": "r", "choices": ["r", "l", "k"] },
  { "id": "Daun", "image": "🍃", "answer": "d", "choices": ["d", "b", "p"] },
  { "id": "Batu", "image": "🪨", "answer": "b", "choices": ["b", "p", "m"] },
  { "id": "Matahari", "image": "☀️", "answer": "m", "choices": ["m", "b", "p"] },
  { "id": "Bulan", "image": "🌙", "answer": "b", "choices": ["b", "m", "p"] },
  { "id": "Bintang", "image": "⭐", "answer": "b", "choices": ["b", "p", "m"] },
  { "id": "Mobil", "image": "🚗", "answer": "m", "choices": ["m", "b", "k"] },
  { "id": "Sepeda", "image": "🚲", "answer": "s", "choices": ["s", "m", "b"] },
  { "id": "Bus", "image": "🚌", "answer": "b", "choices": ["b", "m", "k"] },
  { "id": "Kereta", "image": "🚆", "answer": "k", "choices": ["k", "m", "b"] },
  { "id": "Pesawat", "image": "✈️", "answer": "p", "choices": ["p", "b", "m"] },
  { "id": "Kapal", "image": "⛵", "answer": "k", "choices": ["k", "m", "b"] },
  { "id": "Boneka", "image": "🧸", "answer": "b", "choices": ["b", "p", "m"] },
  { "id": "Bola", "image": "⚽", "answer": "b", "choices": ["b", "p", "m"] },
  { "id": "Balok", "image": "🧱", "answer": "b", "choices": ["b", "p", "m"] },
  { "id": "Kunci", "image": "🔑", "answer": "k", "choices": ["k", "m", "b"] },
  { "id": "Gunting", "image": "✂️", "answer": "g", "choices": ["g", "c", "s"] },
  { "id": "Jagung", "image": "🌽", "answer": "j", "choices": ["j", "c", "g"] },
  { "id": "Sabun", "image": "🧼", "answer": "s", "choices": ["s", "c", "b"] },
  { "id": "Sikat", "image": "🪥", "answer": "s", "choices": ["s", "c", "g"] },
  { "id": "Keju", "image": "🧀", "answer": "k", "choices": ["k", "c", "u"] },
  { "id": "Coklat", "image": "🍫", "answer": "c", "choices": ["t", "c", "k"] },
  { "id": "Tisu", "image": "🧻", "answer": "t", "choices": ["t", "k", "s"] }
];

