export interface AwalKataDataItem {
  id: string;
  image: string;
  answer: string;
  choices: string[];
}

export const awalKataData: AwalKataDataItem[] = [
  { "id": "Mata ", "image": "👁️", "answer": "M", "choices": ["M", "N", "B"] }, 
  { "id": "Hidung", "image": "👃", "answer": "H", "choices": ["H", "N", "M"] },
  { "id": "Mulut", "image": "👄", "answer": "M", "choices": ["M", "B", "P"] },
  { "id": "Telinga", "image": "👂", "answer": "T", "choices": ["T", "D", "P"] },
  { "id": "Tangan", "image": "✋", "answer": "T", "choices": ["T", "K", "P"] },
  { "id": "Kaki", "image": "🦵", "answer": "K", "choices": ["K", "T", "M"] },
  { "id": "Rambut", "image": "💇", "answer": "R", "choices": ["R", "H", "M"] },
  { "id": "Perut", "image": "🧍", "answer": "P", "choices": ["P", "B", "M"] },
  { "id": "Punggung", "image": "🧍", "answer": "P", "choices": ["P", "B", "T"] },
  { "id": "Lutut", "image": "🦵", "answer": "L", "choices": ["L", "S", "T"] },
  { "id": "Siku", "image": "💪", "answer": "S", "choices": ["S", "T", "L"] },
  { "id": "Jari", "image": "👆", "answer": "J", "choices": ["J", "T", "L"] },
  { "id": "Kuku", "image": "💅", "answer": "K", "choices": ["K", "J", "M"] },
  { "id": "Bahu", "image": "💪", "answer": "B", "choices": ["B", "P", "T"] },
  { "id": "Leher", "image": "🧣", "answer": "L", "choices": ["L", "N", "M"] },
  { "id": "Dagu", "image": "🧔", "answer": "D", "choices": ["D", "B", "P"] },
  { "id": "Dahi", "image": "🤔", "answer": "D", "choices": ["D", "P", "M"] },
  { "id": "Alis", "image": "🙄", "answer": "A", "choices": ["A", "M", "H"] },
  { "id": "Bibir", "image": "👄", "answer": "B", "choices": ["B", "M", "P"] },
  { "id": "Gigi", "image": "🦷", "answer": "G", "choices": ["G", "L", "M"] },
  { "id": "Lidah", "image": "👅", "answer": "L", "choices": ["L", "B", "M"] },
  { "id": "Kepala", "image": "🙂", "answer": "K", "choices": ["K", "M", "T"] },
  { "id": "Kursi", "image": "🪑", "answer": "K", "choices": ["K", "M", "T"] },
  { "id": "Meja", "image": "🛋️", "answer": "M", "choices": ["M", "K", "T"] },
  { "id": "Pintu", "image": "🚪", "answer": "P", "choices": ["P", "B", "M"] },
  { "id": "Jendela", "image": "🪟", "answer": "J", "choices": ["J", "P", "M"] },
  { "id": "Lemari", "image": "🗄️", "answer": "L", "choices": ["L", "M", "K"] },
  { "id": "Kasur", "image": "🛏️", "answer": "K", "choices": ["K", "M", "T"] },
  { "id": "Bantal", "image": "🛏️", "answer": "B", "choices": ["B", "P", "K"] },
  { "id": "Cermin", "image": "🪞", "answer": "C", "choices": ["C", "S", "G"] },
  { "id": "Lampu", "image": "💡", "answer": "L", "choices": ["L", "B", "K"] },
  { "id": "Kipas", "image": "🌀", "answer": "K", "choices": ["K", "L", "M"] },
  { "id": "TV", "image": "📺", "answer": "T", "choices": ["T", "K", "L"] },
  { "id": "Radio", "image": "📻", "answer": "R", "choices": ["R", "L", "K"] },
  { "id": "Kompor", "image": "🔥", "answer": "K", "choices": ["K", "M", "L"] },
  { "id": "Wajan", "image": "🍳", "answer": "W", "choices": ["W", "K", "M"] },
  { "id": "Piring", "image": "🍽️", "answer": "P", "choices": ["P", "B", "M"] },
  { "id": "Gelas", "image": "🥤", "answer": "G", "choices": ["G", "C", "B"] },
  { "id": "Sendok", "image": "🥄", "answer": "S", "choices": ["S", "C", "G"] },
  { "id": "Garpu", "image": "🍴", "answer": "G", "choices": ["G", "S", "C"] },
  { "id": "Pisau", "image": "🔪", "answer": "P", "choices": ["P", "G", "S"] },
  { "id": "Nasi", "image": "🍚", "answer": "N", "choices": ["N", "M", "B"] },
  { "id": "Air", "image": "💧", "answer": "A", "choices": ["A", "I", "U"] },
  { "id": "Susu", "image": "🥛", "answer": "S", "choices": ["S", "M", "B"] },
  { "id": "Roti", "image": "🍞", "answer": "R", "choices": ["R", "L", "K"] },
  { "id": "Kue", "image": "🍰", "answer": "K", "choices": ["K", "M", "B"] },
  { "id": "Buah", "image": "🍎", "answer": "B", "choices": ["B", "P", "M"] },
  { "id": "Mangga", "image": "🥭", "answer": "M", "choices": ["M", "B", "P"] },
  { "id": "Pisang", "image": "🍌", "answer": "P", "choices": ["P", "B", "M"] },
  { "id": "Kelapa", "image": "🥥", "answer": "K", "choices": ["K", "M", "G"] },
  { "id": "Jeruk", "image": "🍊", "answer": "J", "choices": ["J", "C", "G"] },
  { "id": "Wortel", "image": "🥕", "answer": "W", "choices": ["W", "K", "M"] },
  { "id": "Ayam", "image": "🐔", "answer": "A", "choices": ["A", "I", "U"] },
  { "id": "Ikan", "image": "🐟", "answer": "I", "choices": ["I", "A", "U"] },
  { "id": "Telur", "image": "🥚", "answer": "T", "choices": ["T", "D", "K"] },
  { "id": "Bunga", "image": "🌸", "answer": "B", "choices": ["B", "P", "M"] },
  { "id": "Pohon", "image": "🌳", "answer": "P", "choices": ["P", "B", "M"] },
  { "id": "Rumput", "image": "🌱", "answer": "R", "choices": ["R", "L", "K"] },
  { "id": "Daun", "image": "🍃", "answer": "D", "choices": ["D", "B", "P"] },
  { "id": "Batu", "image": "🪨", "answer": "B", "choices": ["B", "P", "M"] },
  { "id": "Matahari", "image": "☀️", "answer": "M", "choices": ["M", "B", "P"] },
  { "id": "Bulan", "image": "🌙", "answer": "B", "choices": ["B", "M", "P"] },
  { "id": "Bintang", "image": "⭐", "answer": "B", "choices": ["B", "P", "M"] },
  { "id": "Mobil", "image": "🚗", "answer": "M", "choices": ["M", "B", "K"] },
  { "id": "Sepeda", "image": "🚲", "answer": "S", "choices": ["S", "M", "B"] },
  { "id": "Bus", "image": "🚌", "answer": "B", "choices": ["B", "M", "K"] },
  { "id": "Kereta", "image": "🚆", "answer": "K", "choices": ["K", "M", "B"] },
  { "id": "Pesawat", "image": "✈️", "answer": "P", "choices": ["P", "B", "M"] },
  { "id": "Kapal", "image": "⛵", "answer": "K", "choices": ["K", "M", "B"] },
  { "id": "Boneka", "image": "🧸", "answer": "B", "choices": ["B", "P", "M"] },
  { "id": "Bola", "image": "⚽", "answer": "B", "choices": ["B", "P", "M"] },
  { "id": "Balok", "image": "🧱", "answer": "B", "choices": ["B", "P", "M"] },
  { "id": "Kunci", "image": "🔑", "answer": "K", "choices": ["K", "M", "B"] },
  { "id": "Gunting", "image": "✂️", "answer": "G", "choices": ["G", "C", "S"] },
  { "id": "Saputangan", "image": "🧻", "answer": "S", "choices": ["S", "C", "G"] },
  { "id": "Sabun", "image": "🧼", "answer": "S", "choices": ["S", "C", "B"] },
  { "id": "Sikat", "image": "🪥", "answer": "S", "choices": ["S", "C", "G"] },
  { "id": "Sampo", "image": "🧴", "answer": "S", "choices": ["S", "C", "G"] },
  { "id": "Handuk", "image": "🛁", "answer": "H", "choices": ["H", "S", "K"] },
  { "id": "Tisu", "image": "🧻", "answer": "T", "choices": ["T", "K", "S"] }
];

