export interface AkhirKataDataItem {
  id: string;
  image: string;
  answer: string;
  choices: string[];
}

export const akhirKataData: AkhirKataDataItem[] = [
  { "id": "Mata", "image": "👁️", "answer": "a", "choices": ["z","o","a"] },
  { "id": "Hidung", "image": "👃", "answer": "g", "choices": ["u","g","a"] },
  { "id": "Mulut", "image": "👄", "answer": "t", "choices": ["d","t","y"] },
  { "id": "Telinga", "image": "👂", "answer": "a", "choices": ["r","d","a"] },
  { "id": "Tangan", "image": "✋", "answer": "n", "choices": ["r","n","a"] },
  { "id": "Kaki", "image": "🦵", "answer": "i", "choices": ["i","n","c"] },
  { "id": "Rambut", "image": "💇", "answer": "t", "choices": ["t","e","n"] },
  { "id": "Badak", "image": "🦏", "answer": "k", "choices": ["o","l","k"] },
  { "id": "Nyamuk", "image": "🦟", "answer": "k", "choices": ["e","i","k"] },
  { "id": "Lutut", "image": "🦵", "answer": "t", "choices": ["v","t","u"] },
  { "id": "Otot", "image": "💪", "answer": "t", "choices": ["y","a","t"] },
  { "id": "Jari", "image": "👆", "answer": "i", "choices": ["x","i","q"] },
  { "id": "Kuku", "image": "💅", "answer": "u", "choices": ["d","u","t"] },
  { "id": "Mawar", "image": "🌹", "answer": "r", "choices": ["w","c","r"] },
  { "id": "Bulan", "image": "🌙", "answer": "n", "choices": ["z","n","a"] },
  { "id": "Meteor", "image": "☄️", "answer": "r", "choices": ["v","r","c"] },
  { "id": "Tornado", "image": "🌪️", "answer": "o", "choices": ["j","a","o"] },
  { "id": "Petir", "image": "⚡", "answer": "r", "choices": ["k","l","r"] },
  { "id": "Bibir", "image": "👄", "answer": "r", "choices": ["r","x","c"] },
  { "id": "Gigi", "image": "🦷", "answer": "i", "choices": ["i","t","d"] },
  { "id": "Lidah", "image": "👅", "answer": "h", "choices": ["h","c","k"] },
  { "id": "Kiwi", "image": "🥝", "answer": "i", "choices": ["l","i","t"] },
  { "id": "Kursi", "image": "🪑", "answer": "i", "choices": ["x","b","i"] },
  { "id": "Sofa", "image": "🛋️", "answer": "a", "choices": ["a","h","q"] },
  { "id": "Pintu", "image": "🚪", "answer": "u", "choices": ["h","u","m"] },
  { "id": "Jendela", "image": "🪟", "answer": "a", "choices": ["d","a","n"] },
  { "id": "Lemari", "image": "🗄️", "answer": "i", "choices": ["i","x","n"] },
  { "id": "Kasur", "image": "🛏️", "answer": "r", "choices": ["r","w","o"] },
  { "id": "Toples", "image": "🫙", "answer": "s", "choices": ["y","s","d"] },
  { "id": "Cermin", "image": "🪞", "answer": "n", "choices": ["z","a","n"] },
  { "id": "Lampu", "image": "💡", "answer": "u", "choices": ["u","j","m"] },
  { "id": "Sumpit", "image": "🥢", "answer": "t", "choices": ["i","t","o"] },
  { "id": "TV", "image": "📺", "answer": "v", "choices": ["q","n","v"] },
  { "id": "Radio", "image": "📻", "answer": "o", "choices": ["o","k","m"] },
  { "id": "Api", "image": "🔥", "answer": "i", "choices": ["i","l","z"] },
  { "id": "Wajan", "image": "🍳", "answer": "n", "choices": ["n","p","q"] },
  { "id": "Piring", "image": "🍽️", "answer": "g", "choices": ["r","g","u"] },
  { "id": "Gelas", "image": "🥤", "answer": "s", "choices": ["s","w","j"] },
  { "id": "Sendok", "image": "🥄", "answer": "k", "choices": ["k","h","n"] },
  { "id": "Garpu", "image": "🍴", "answer": "u", "choices": ["e","i","u"] },
  { "id": "Pisau", "image": "🔪", "answer": "u", "choices": ["r","u","f"] },
  { "id": "Nasi", "image": "🍚", "answer": "i", "choices": ["t","i","d"] },
  { "id": "Air", "image": "💧", "answer": "r", "choices": ["t","r","l"] },
  { "id": "Susu", "image": "🥛", "answer": "u", "choices": ["n","r","u"] },
  { "id": "Roti", "image": "🍞", "answer": "i", "choices": ["l","i","d"] },
  { "id": "Kue", "image": "🍰", "answer": "e", "choices": ["w","p","e"] },
  { "id": "Buah", "image": "🍎", "answer": "h", "choices": ["j","i","h"] },
  { "id": "Mangga", "image": "🥭", "answer": "a", "choices": ["p","i","a"] },
  { "id": "Pisang", "image": "🍌", "answer": "g", "choices": ["w","g","v"] },
  { "id": "Kelapa", "image": "🥥", "answer": "a", "choices": ["m","a","u"] },
  { "id": "Jeruk", "image": "🍊", "answer": "k", "choices": ["u","k","r"] },
  { "id": "Wortel", "image": "🥕", "answer": "l", "choices": ["l","i","h"] },
  { "id": "Ayam", "image": "🐔", "answer": "m", "choices": ["q","m","o"] },
  { "id": "Ikan", "image": "🐟", "answer": "n", "choices": ["n","b","v"] },
  { "id": "Telur", "image": "🥚", "answer": "r", "choices": ["r","i","f"] },
  { "id": "Bunga", "image": "🌸", "answer": "a", "choices": ["a","h","x"] },
  { "id": "Pohon", "image": "🌳", "answer": "n", "choices": ["n","v","r"] },
  { "id": "Rumput", "image": "🌱", "answer": "t", "choices": ["t","y","l"] },
  { "id": "Daun", "image": "🍃", "answer": "n", "choices": ["p","n","o"] },
  { "id": "Batu", "image": "🪨", "answer": "u", "choices": ["u","y","z"] },
  { "id": "Matahari", "image": "☀️", "answer": "i", "choices": ["i","q","a"] },
  { "id": "Bulan", "image": "🌙", "answer": "n", "choices": ["j","o","n"] },
  { "id": "Bintang", "image": "⭐", "answer": "g", "choices": ["g","d","h"] },
  { "id": "Mobil", "image": "🚗", "answer": "l", "choices": ["l","f","h"] },
  { "id": "Sepeda", "image": "🚲", "answer": "a", "choices": ["a","u","z"] },
  { "id": "Bus", "image": "🚌", "answer": "s", "choices": ["s","q","h"] },
  { "id": "Kereta", "image": "🚆", "answer": "a", "choices": ["v","a","y"] },
  { "id": "Pesawat", "image": "✈️", "answer": "t", "choices": ["j","r","t"] },
  { "id": "Kapal", "image": "⛵", "answer": "l", "choices": ["t","b","l"] },
  { "id": "Boneka", "image": "🧸", "answer": "a", "choices": ["q","a","d"] },
  { "id": "Bola", "image": "⚽", "answer": "a", "choices": ["a","t","x"] },
  { "id": "Balok", "image": "🧱", "answer": "k", "choices": ["k","l","n"] },
  { "id": "Kunci", "image": "🔑", "answer": "i", "choices": ["e","q","i"] },
  { "id": "Gunting", "image": "✂️", "answer": "g", "choices": ["g","c","x"] },
  { "id": "Jagung", "image": "🌽", "answer": "g", "choices": ["o","g","k"] },
  { "id": "Sabun", "image": "🧼", "answer": "n", "choices": ["n","m","t"] },
  { "id": "Sikat", "image": "🪥", "answer": "t", "choices": ["t","k","s"] },
  { "id": "Keju", "image": "🧀", "answer": "u", "choices": ["c","u","f"] },
  { "id": "Coklat", "image": "🍫", "answer": "t", "choices": ["x","t","k"] },
  { "id": "Tisu", "image": "🧻", "answer": "u", "choices": ["p","w","u"] }
];
