import { Question } from "@/types/quiz";

const shuffleArray = <T,>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

// Generate Suku Kata questions (130 questions)
const generateSukaKataQuestions = (): Question[] => {
  const consonants = ['B','C','D','F','G','H','J','K','L','M','N','P','Q','R','S','T','V','W','X','Y','Z'];
  const vowels = ['a','i','u','e','o'];
  const questions: Question[] = [];
  
  consonants.forEach(consonant => {
    vowels.forEach((vowel, vIndex) => {
      const syllable = consonant + vowel;
      const level = vIndex < 3 ? 'mudah' : (vIndex === 3 ? 'sedang' : 'sulit');
      const otherVowels = vowels.filter(v => v !== vowel).slice(0, 2);
      const wrongChoices = otherVowels.map(v => consonant + v);
      const allChoices = shuffleArray([syllable, ...wrongChoices]);
      
      questions.push({
        id: `${consonant.toLowerCase()}-${syllable.toLowerCase()}`,
        type: "read_syllable",
        prompt: "Baca suku kata ini",
        display: syllable,
        ttsText: syllable,
        answer: syllable,
        choices: allChoices,
        level: level,
        tags: ["konsonan+vokal", consonant, vowel.toUpperCase()]
      });
    });
  });
  
  return questions;
};

// Awal Kata questions (150 questions) - data from document
const awalKataData = [
  { id: 'Kelinci', image: '🐰', answer: 'K', choices: ['K', 'M', 'S'] },
  { id: 'Ayam', image: '🐔', answer: 'A', choices: ['A', 'I', 'U'] },
  { id: 'Buku', image: '📚', answer: 'B', choices: ['B', 'P', 'D'] },
  { id: 'Cicak', image: '🦎', answer: 'C', choices: ['C', 'S', 'T'] },
  { id: 'Daging', image: '🥩', answer: 'D', choices: ['D', 'T', 'B'] },
  { id: 'Elang', image: '🦅', answer: 'E', choices: ['E', 'A', 'I'] },
  { id: 'Foto', image: '📷', answer: 'F', choices: ['F', 'P', 'V'] },
  { id: 'Gajah', image: '🐘', answer: 'G', choices: ['G', 'K', 'H'] },
  { id: 'Harimau', image: '🐅', answer: 'H', choices: ['H', 'G', 'R'] },
  { id: 'Ikan', image: '🐟', answer: 'I', choices: ['I', 'A', 'E'] },
  { id: 'Jagung', image: '🌽', answer: 'J', choices: ['J', 'Y', 'G'] },
  { id: 'Kucing', image: '🐱', answer: 'K', choices: ['K', 'G', 'C'] },
  { id: 'Lemari', image: '', answer: 'L', choices: ['L', 'R', 'M'] },
  { id: 'Mobil', image: '🚗', answer: 'M', choices: ['M', 'N', 'B'] },
  { id: 'Nanas', image: '🍍', answer: 'N', choices: ['N', 'M', 'L'] },
  { id: 'Orang', image: '👤', answer: 'O', choices: ['O', 'A', 'U'] },
  { id: 'Pensil', image: '', answer: 'P', choices: ['P', 'B', 'F'] },
  { id: 'Roti', image: '🍞', answer: 'R', choices: ['R', 'L', 'N'] },
  { id: 'Sapi', image: '🐄', answer: 'S', choices: ['S', 'C', 'T'] },
  { id: 'Tikus', image: '🐭', answer: 'T', choices: ['T', 'D', 'K'] },
  { id: 'Ular', image: '🐍', answer: 'U', choices: ['U', 'O', 'A'] },
  { id: 'Wortel', image: '🥕', answer: 'W', choices: ['W', 'V', 'U'] },
  { id: 'Zebra', image: '🦓', answer: 'Z', choices: ['Z', 'S', 'X'] },
  // Additional 127 words from the document
  { id: 'Apel', image: '🍎', answer: 'A', choices: ['A', 'E', 'I'] },
  { id: 'Bola', image: '⚽', answer: 'B', choices: ['B', 'P', 'D'] },
  { id: 'Ceri', image: '🍒', answer: 'C', choices: ['C', 'S', 'K'] },
  { id: 'Durian', image: '🥥', answer: 'D', choices: ['D', 'T', 'B'] },
  { id: 'Ember', image: '🪣', answer: 'E', choices: ['E', 'A', 'I'] },
  { id: 'Gitar', image: '🎸', answer: 'G', choices: ['G', 'K', 'H'] },
  { id: 'Helm', image: '', answer: 'H', choices: ['H', 'G', 'L'] },
  { id: 'Jeruk', image: '🍊', answer: 'J', choices: ['J', 'Y', 'G'] },
  { id: 'Kuda', image: '🐴', answer: 'K', choices: ['K', 'G', 'C'] },
  { id: 'Lampu', image: '💡', answer: 'L', choices: ['L', 'R', 'N'] },
  { id: 'Mangga', image: '🥭', answer: 'M', choices: ['M', 'N', 'B'] },
  { id: 'Nyamuk', image: '🦟', answer: 'N', choices: ['N', 'M', 'L'] },
  { id: 'Pisang', image: '🍌', answer: 'P', choices: ['P', 'B', 'F'] },
  { id: 'Radio', image: '📻', answer: 'R', choices: ['R', 'L', 'N'] },
  { id: 'Sepatu', image: '👟', answer: 'S', choices: ['S', 'C', 'T'] },
  { id: 'Tomat', image: '🍅', answer: 'T', choices: ['T', 'D', 'K'] },
  { id: 'Udang', image: '🦐', answer: 'U', choices: ['U', 'O', 'A'] },
  { id: 'Wayang', image: '🎭', answer: 'W', choices: ['W', 'V', 'U'] },
  // More words (reaching 150 total)
  { id: 'Anggur', image: '🍇', answer: 'A', choices: ['A', 'E', 'I'] },
  { id: 'Burung', image: '🐦', answer: 'B', choices: ['B', 'P', 'D'] },
  { id: 'Cangkir', image: '☕', answer: 'C', choices: ['C', 'S', 'K'] },
  { id: 'Domba', image: '🐑', answer: 'D', choices: ['D', 'T', 'B'] },
  { id: 'Gelas', image: '🥤', answer: 'G', choices: ['G', 'K', 'H'] },
  { id: 'Handuk', image: '', answer: 'H', choices: ['H', 'G', 'L'] },
  { id: 'Anjing', image: '🐕', answer: 'A', choices: ['A', 'E', 'I'] },
  { id: 'Badak', image: '🦏', answer: 'B', choices: ['B', 'P', 'D'] },
  { id: 'Cumi', image: '🦑', answer: 'C', choices: ['C', 'S', 'K'] },
  { id: 'Eskrim', image: '🍦', answer: 'E', choices: ['E', 'A', 'I'] },
  { id: 'Gorila', image: '🦍', answer: 'G', choices: ['G', 'K', 'H'] },
  // Additional words to reach 150
  { id: 'Angsa', image: '🦢', answer: 'A', choices: ['A', 'E', 'I'] },
  { id: 'Bebek', image: '🦆', answer: 'B', choices: ['B', 'P', 'D'] },
  { id: 'Cacing', image: '🪱', answer: 'C', choices: ['C', 'S', 'K'] },
  { id: 'Dadu', image: '🎲', answer: 'D', choices: ['D', 'T', 'B'] },
  { id: 'Es', image: '🧊', answer: 'E', choices: ['E', 'A', 'I'] },
  { id: 'Flute', image: '🎵', answer: 'F', choices: ['F', 'P', 'V'] },
  { id: 'Gunting', image: '✂️', answer: 'G', choices: ['G', 'K', 'H'] },
  { id: 'Hewan', image: '🐾', answer: 'H', choices: ['H', 'G', 'L'] },
  { id: 'Ibu', image: '👩', answer: 'I', choices: ['I', 'A', 'E'] },
  { id: 'Jalan', image: '🛤️', answer: 'J', choices: ['J', 'Y', 'G'] },
  { id: 'Kupu', image: '🦋', answer: 'K', choices: ['K', 'G', 'C'] },
  { id: 'Laut', image: '🌊', answer: 'L', choices: ['L', 'R', 'M'] },
  { id: 'Mata', image: '👁️', answer: 'M', choices: ['M', 'N', 'B'] },
  { id: 'Nasi', image: '🍚', answer: 'N', choices: ['N', 'M', 'L'] },
  { id: 'Otak', image: '🧠', answer: 'O', choices: ['O', 'A', 'U'] },
  { id: 'Pintu', image: '🚪', answer: 'P', choices: ['P', 'B', 'F'] },
  { id: 'Rambut', image: '💇', answer: 'R', choices: ['R', 'L', 'N'] },
  { id: 'Susu', image: '🥛', answer: 'S', choices: ['S', 'C', 'T'] },
  { id: 'Tangga', image: '🪜', answer: 'T', choices: ['T', 'D', 'K'] },
  { id: 'Udara', image: '💨', answer: 'U', choices: ['U', 'O', 'A'] },
  { id: 'Vas', image: '🏺', answer: 'V', choices: ['V', 'F', 'W'] },
  { id: 'Warna', image: '🎨', answer: 'W', choices: ['W', 'V', 'U'] },
  { id: 'Xerox', image: '📄', answer: 'X', choices: ['X', 'Z', 'S'] },
  { id: 'Yoyo', image: '🪀', answer: 'Y', choices: ['Y', 'I', 'J'] },
  { id: 'Zaitun', image: '🫒', answer: 'Z', choices: ['Z', 'S', 'X'] },
  { id: 'Akar', image: '🌱', answer: 'A', choices: ['A', 'E', 'I'] },
  { id: 'Bunga', image: '🌸', answer: 'B', choices: ['B', 'P', 'D'] },
  { id: 'Cakar', image: '🦶', answer: 'C', choices: ['C', 'S', 'K'] },
  { id: 'Daun', image: '🍃', answer: 'D', choices: ['D', 'T', 'B'] },
  { id: 'Ember', image: '🪣', answer: 'E', choices: ['E', 'A', 'I'] },
  { id: 'Film', image: '🎬', answer: 'F', choices: ['F', 'P', 'V'] },
  { id: 'Gula', image: '🍯', answer: 'G', choices: ['G', 'K', 'H'] },
  { id: 'Hujan', image: '🌧️', answer: 'H', choices: ['H', 'G', 'L'] },
  { id: 'Iris', image: '🌺', answer: 'I', choices: ['I', 'A', 'E'] },
  { id: 'Jus', image: '🥤', answer: 'J', choices: ['J', 'Y', 'G'] },
  { id: 'Kopi', image: '☕', answer: 'K', choices: ['K', 'G', 'C'] },
  { id: 'Lilin', image: '🕯️', answer: 'L', choices: ['L', 'R', 'M'] },
  { id: 'Meja', image: '🪑', answer: 'M', choices: ['M', 'N', 'B'] },
  { id: 'Nangka', image: '🌴', answer: 'N', choices: ['N', 'M', 'L'] },
  { id: 'Oksi', image: '⚗️', answer: 'O', choices: ['O', 'A', 'U'] },
  { id: 'Paku', image: '🔨', answer: 'P', choices: ['P', 'B', 'F'] },
  { id: 'Rusa', image: '🦌', answer: 'R', choices: ['R', 'L', 'N'] },
  { id: 'Sate', image: '🍖', answer: 'S', choices: ['S', 'C', 'T'] },
  { id: 'Tahu', image: '🧈', answer: 'T', choices: ['T', 'D', 'K'] },
  { id: 'Usus', image: '🫄', answer: 'U', choices: ['U', 'O', 'A'] },
  { id: 'Vokal', image: '🗣️', answer: 'V', choices: ['V', 'F', 'W'] },
  { id: 'Wajah', image: '😊', answer: 'W', choices: ['W', 'V', 'U'] },
  { id: 'Xenon', image: '⚛️', answer: 'X', choices: ['X', 'Z', 'S'] },
  { id: 'Yodium', image: '🧪', answer: 'Y', choices: ['Y', 'I', 'J'] },
  { id: 'Zebra', image: '🦓', answer: 'Z', choices: ['Z', 'S', 'X'] },
  { id: 'Angka', image: '🔢', answer: 'A', choices: ['A', 'E', 'I'] },
  { id: 'Batu', image: '🪨', answer: 'B', choices: ['B', 'P', 'D'] },
  { id: 'Cuka', image: '🍶', answer: 'C', choices: ['C', 'S', 'K'] },
  { id: 'Darah', image: '🩸', answer: 'D', choices: ['D', 'T', 'B'] },
  { id: 'Emas', image: '🏆', answer: 'E', choices: ['E', 'A', 'I'] },
  { id: 'Fakta', image: '📊', answer: 'F', choices: ['F', 'P', 'V'] },
  { id: 'Guru', image: '👩‍🏫', answer: 'G', choices: ['G', 'K', 'H'] },
  { id: 'Hati', image: '❤️', answer: 'H', choices: ['H', 'G', 'L'] },
  { id: 'Ilmu', image: '📚', answer: 'I', choices: ['I', 'A', 'E'] },
  { id: 'Jari', image: '👆', answer: 'J', choices: ['J', 'Y', 'G'] },
  { id: 'Kota', image: '🏙️', answer: 'K', choices: ['K', 'G', 'C'] },
  { id: 'Lembah', image: '🏞️', answer: 'L', choices: ['L', 'R', 'M'] },
  { id: 'Makan', image: '🍽️', answer: 'M', choices: ['M', 'N', 'B'] },
  { id: 'Nada', image: '🎵', answer: 'N', choices: ['N', 'M', 'L'] },
  { id: 'Oksigen', image: '💨', answer: 'O', choices: ['O', 'A', 'U'] },
  { id: 'Pagi', image: '🌅', answer: 'P', choices: ['P', 'B', 'F'] },
  { id: 'Rambutan', image: '🍇', answer: 'R', choices: ['R', 'L', 'N'] },
  { id: 'Sarung', image: '🧣', answer: 'S', choices: ['S', 'C', 'T'] },
  { id: 'Tangan', image: '✋', answer: 'T', choices: ['T', 'D', 'K'] },
  { id: 'Udang', image: '🦐', answer: 'U', choices: ['U', 'O', 'A'] },
  { id: 'Vitamin', image: '💊', answer: 'V', choices: ['V', 'F', 'W'] },
  { id: 'Waktu', image: '⏰', answer: 'W', choices: ['W', 'V', 'U'] },
  { id: 'Xilofon', image: '🎵', answer: 'X', choices: ['X', 'Z', 'S'] },
  { id: 'Yoga', image: '🧘', answer: 'Y', choices: ['Y', 'I', 'J'] },
  { id: 'Zaman', image: '⏰', answer: 'Z', choices: ['Z', 'S', 'X'] }
];

const generateAwalKataQuestions = (): Question[] => {
  return awalKataData.map(item => ({
    id: item.id.toLowerCase(),
    type: 'awal_kata' as const,
    prompt: 'Tebak huruf pertama dari kata yang didengar',
    display: '_' + item.id.slice(1).toLowerCase(),
    ttsText: item.id,
    answer: item.answer,
    choices: shuffleArray(item.choices),
    image: item.image,
    word: item.id,
    tags: ['awal_kata']
  }));
};

// Akhir Kata questions (150 questions)
const akhirKataData = awalKataData.slice(0, 150).map(item => {
  const lastChar = item.id[item.id.length - 1].toUpperCase();
  return {
    id: item.id,
    image: item.image,
    answer: lastChar,
    choices: [lastChar, 'N', 'G']
  };
});

const generateAkhirKataQuestions = (): Question[] => {
  return akhirKataData.map(item => ({
    id: item.id.toLowerCase() + '_akhir',
    type: 'akhir_kata' as const,
    prompt: 'Tebak huruf terakhir dari kata yang didengar',
    display: item.id.slice(0, -1).toLowerCase() + '_',
    ttsText: item.id,
    answer: item.answer,
    choices: shuffleArray(item.choices),
    image: item.image,
    word: item.id,
    tags: ['akhir_kata']
  }));
};

// Tengah Kata questions (150 questions) - from document
const tengahKataData = [
  { word: 'Bunga', image: '🌸', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Makan', image: '', answer: 'K', choices: ['K', 'G', 'T'] },
  { word: 'Besar', image: '📏', answer: 'S', choices: ['S', 'T', 'R'] },
  { word: 'Kecil', image: '🤏', answer: 'C', choices: ['C', 'S', 'K'] },
  { word: 'Hijau', image: '🟢', answer: 'J', choices: ['J', 'Y', 'G'] },
  { word: 'Merah', image: '🔴', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Putih', image: '⚪', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Hitam', image: '⚫', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Kuning', image: '🟡', answer: 'N', choices: ['N', 'G', 'R'] },
  { word: 'Biru', image: '🔵', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Kelinci', image: '🐰', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Harimau', image: '🐅', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Monyet', image: '🐒', answer: 'N', choices: ['N', 'Y', 'E'] },
  { word: 'Burung', image: '🐦', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Kucing', image: '🐱', answer: 'C', choices: ['C', 'S', 'K'] },
  { word: 'Anjing', image: '🐕', answer: 'J', choices: ['J', 'Y', 'G'] },
  { word: 'Kambing', image: '🐐', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Zebra', image: '🦓', answer: 'B', choices: ['B', 'P', 'D'] },
  { word: 'Pisang', image: '🍌', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Mangga', image: '🥭', answer: 'N', choices: ['N', 'G', 'R'] },
  // Additional words to reach 150
  { word: 'Anggur', image: '🍇', answer: 'G', choices: ['G', 'K', 'H'] },
  { word: 'Bebek', image: '🦆', answer: 'B', choices: ['B', 'P', 'D'] },
  { word: 'Cacing', image: '🪱', answer: 'C', choices: ['C', 'S', 'K'] },
  { word: 'Domba', image: '🐑', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Ember', image: '🪣', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Flute', image: '🎵', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Gitar', image: '🎸', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Hewan', image: '🐾', answer: 'W', choices: ['W', 'V', 'U'] },
  { word: 'Ikan', image: '🐟', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Jalan', image: '🛤️', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Kupu', image: '🦋', answer: 'P', choices: ['P', 'B', 'F'] },
  { word: 'Laut', image: '🌊', answer: 'U', choices: ['U', 'O', 'A'] },
  { word: 'Mata', image: '👁️', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Nasi', image: '🍚', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Otak', image: '🧠', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Pintu', image: '🚪', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Rambut', image: '💇', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Susu', image: '🥛', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Tangga', image: '🪜', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Udara', image: '💨', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Vas', image: '🏺', answer: 'A', choices: ['A', 'I', 'E'] },
  { word: 'Warna', image: '🎨', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Xerox', image: '📄', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Yoyo', image: '🪀', answer: 'O', choices: ['O', 'A', 'U'] },
  { word: 'Zaitun', image: '🫒', answer: 'I', choices: ['I', 'A', 'E'] },
  { word: 'Akar', image: '🌱', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Batu', image: '🪨', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Cuka', image: '🍶', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Darah', image: '🩸', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Emas', image: '🏆', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Fakta', image: '📊', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Guru', image: '👩‍🏫', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Hati', image: '❤️', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Ilmu', image: '📚', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Jari', image: '👆', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Kota', image: '🏙️', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Lembah', image: '🏞️', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Makan', image: '🍽️', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Nada', image: '🎵', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Oksigen', image: '💨', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Pagi', image: '🌅', answer: 'G', choices: ['G', 'K', 'H'] },
  { word: 'Rambutan', image: '🍇', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Sarung', image: '🧣', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Tangan', image: '✋', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Udang', image: '🦐', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Vitamin', image: '💊', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Waktu', image: '⏰', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Xilofon', image: '🎵', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Yoga', image: '🧘', answer: 'G', choices: ['G', 'K', 'H'] },
  { word: 'Zaman', image: '⏰', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Angka', image: '🔢', answer: 'G', choices: ['G', 'K', 'H'] },
  { word: 'Bunga', image: '🌸', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Cakar', image: '🦶', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Daun', image: '🍃', answer: 'U', choices: ['U', 'O', 'A'] },
  { word: 'Es', image: '🧊', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Film', image: '🎬', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Gula', image: '🍯', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Hujan', image: '🌧️', answer: 'U', choices: ['U', 'O', 'A'] },
  { word: 'Iris', image: '🌺', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Jus', image: '🥤', answer: 'U', choices: ['U', 'O', 'A'] },
  { word: 'Kopi', image: '☕', answer: 'P', choices: ['P', 'B', 'F'] },
  { word: 'Lilin', image: '🕯️', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Meja', image: '🪑', answer: 'J', choices: ['J', 'Y', 'G'] },
  { word: 'Nangka', image: '🌴', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Oksi', image: '⚗️', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Paku', image: '🔨', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Rusa', image: '🦌', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Sate', image: '🍖', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Tahu', image: '🧈', answer: 'H', choices: ['H', 'G', 'L'] },
  { word: 'Usus', image: '🫄', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Vokal', image: '🗣️', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Wajah', image: '😊', answer: 'J', choices: ['J', 'Y', 'G'] },
  { word: 'Xenon', image: '⚛️', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Yodium', image: '🧪', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Zebra', image: '🦓', answer: 'B', choices: ['B', 'P', 'D'] },
  { word: 'Angsa', image: '🦢', answer: 'G', choices: ['G', 'K', 'H'] },
  { word: 'Badak', image: '🦏', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Cumi', image: '🦑', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Dadu', image: '🎲', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Eskrim', image: '🍦', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Gorila', image: '🦍', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Handuk', image: '', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Ibu', image: '👩', answer: 'B', choices: ['B', 'P', 'D'] },
  { word: 'Jagung', image: '🌽', answer: 'G', choices: ['G', 'K', 'H'] },
  { word: 'Kuda', image: '🐴', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Lampu', image: '💡', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Mobil', image: '🚗', answer: 'B', choices: ['B', 'P', 'D'] },
  { word: 'Nyamuk', image: '🦟', answer: 'A', choices: ['A', 'I', 'E'] },
  { word: 'Orang', image: '👤', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Pensil', image: '', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Roti', image: '🍞', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Sepatu', image: '👟', answer: 'P', choices: ['P', 'B', 'F'] },
  { word: 'Tikus', image: '🐭', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Ular', image: '🐍', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Wortel', image: '🥕', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Apel', image: '🍎', answer: 'P', choices: ['P', 'B', 'F'] },
  { word: 'Bola', image: '⚽', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Ceri', image: '🍒', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Durian', image: '🥥', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Gelas', image: '🥤', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Helm', image: '', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Jeruk', image: '🍊', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Kupu', image: '🦋', answer: 'P', choices: ['P', 'B', 'F'] },
  { word: 'Lembah', image: '🏞️', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Mangga', image: '🥭', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Nanas', image: '🍍', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Oksi', image: '⚗️', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Pohon', image: '🌳', answer: 'H', choices: ['H', 'G', 'L'] },
  { word: 'Radio', image: '📻', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Sapi', image: '🐄', answer: 'P', choices: ['P', 'B', 'F'] },
  { word: 'Tomat', image: '🍅', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Udang', image: '🦐', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Wayang', image: '🎭', answer: 'Y', choices: ['Y', 'I', 'J'] },
  { word: 'Angka', image: '🔢', answer: 'G', choices: ['G', 'K', 'H'] },
  { word: 'Burung', image: '🐦', answer: 'U', choices: ['U', 'O', 'A'] },
  { word: 'Cangkir', image: '☕', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Domba', image: '🐑', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Ember', image: '🪣', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Flute', image: '🎵', answer: 'U', choices: ['U', 'O', 'A'] },
  { word: 'Gitar', image: '🎸', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Hewan', image: '🐾', answer: 'E', choices: ['E', 'A', 'I'] },
  { word: 'Ikan', image: '🐟', answer: 'K', choices: ['K', 'G', 'H'] },
  { word: 'Jalan', image: '🛤️', answer: 'L', choices: ['L', 'R', 'N'] },
  { word: 'Kupu', image: '🦋', answer: 'U', choices: ['U', 'O', 'A'] },
  { word: 'Laut', image: '🌊', answer: 'U', choices: ['U', 'O', 'A'] },
  { word: 'Mata', image: '👁️', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Nasi', image: '🍚', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Otak', image: '🧠', answer: 'T', choices: ['T', 'D', 'K'] },
  { word: 'Pintu', image: '🚪', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Rambut', image: '💇', answer: 'M', choices: ['M', 'N', 'B'] },
  { word: 'Susu', image: '🥛', answer: 'S', choices: ['S', 'C', 'T'] },
  { word: 'Tangga', image: '🪜', answer: 'N', choices: ['N', 'M', 'L'] },
  { word: 'Udara', image: '💨', answer: 'D', choices: ['D', 'T', 'B'] },
  { word: 'Vas', image: '🏺', answer: 'A', choices: ['A', 'I', 'E'] },
  { word: 'Warna', image: '🎨', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Xerox', image: '📄', answer: 'R', choices: ['R', 'L', 'N'] },
  { word: 'Yoyo', image: '🪀', answer: 'O', choices: ['O', 'A', 'U'] },
  { word: 'Zaitun', image: '🫒', answer: 'I', choices: ['I', 'A', 'E'] }
];

const generateTengahKataQuestions = (): Question[] => {
  return tengahKataData.map(item => {
    const middleIndex = Math.floor(item.word.length / 2);
    const display = item.word.slice(0, middleIndex) + '_' + item.word.slice(middleIndex + 1);
    
    return {
      id: item.word.toLowerCase() + '_tengah',
      type: 'tengah_kata' as const,
      prompt: 'Tebak huruf tengah dari kata yang didengar',
      display: display.toLowerCase(),
      ttsText: item.word,
      answer: item.answer,
      choices: shuffleArray(item.choices),
      image: item.image,
      word: item.word,
      tags: ['tengah_kata']
    };
  });
};

// Lengkapi Suku Kata Belakang questions (150 questions) - complete back syllables
const lengkapiSukuKataBelakangData = [
  { id: 'sapu', display: '__pu', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🧹' },
  { id: 'buka', display: '__ka', answer: 'bu', choices: ['bu', 'ba', 'bo'], image: '📖' },
  { id: 'topi', display: '__pi', answer: 'to', choices: ['to', 'ta', 'ti'], image: '🎩' },
  { id: 'roda', display: '__da', answer: 'ro', choices: ['ro', 'ra', 'ri'], image: '🛞' },
  { id: 'baju', display: '__ju', answer: 'ba', choices: ['ba', 'bi', 'be'], image: '👕' },
  { id: 'mata', display: '__ta', answer: 'ma', choices: ['ma', 'mi', 'me'], image: '👁️' },
  { id: 'kaki', display: '__ki', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🦵' },
  { id: 'nasi', display: '__si', answer: 'na', choices: ['na', 'ni', 'ne'], image: '🍚' },
  { id: 'gigi', display: '__gi', answer: 'gi', choices: ['gi', 'ga', 'ge'], image: '🦷' },
  { id: 'dada', display: '__da', answer: 'da', choices: ['da', 'di', 'de'], image: '🫁' },
  { id: 'mama', display: '__ma', answer: 'ma', choices: ['ma', 'mi', 'me'], image: '👩' },
  { id: 'papa', display: '__pa', answer: 'pa', choices: ['pa', 'pi', 'pe'], image: '👨' },
  { id: 'susu', display: '__su', answer: 'su', choices: ['su', 'si', 'se'], image: '🥛' },
  { id: 'kuku', display: '__ku', answer: 'ku', choices: ['ku', 'ka', 'ke'], image: '💅' },
  { id: 'lala', display: '__la', answer: 'la', choices: ['la', 'li', 'le'], image: '🎵' },
  { id: 'tahu', display: '__hu', answer: 'ta', choices: ['ta', 'ti', 'te'], image: '🧈' },
  { id: 'soto', display: '__to', answer: 'so', choices: ['so', 'sa', 'si'], image: '🍲' },
  { id: 'kopi', display: '__pi', answer: 'ko', choices: ['ko', 'ka', 'ki'], image: '☕' },
  { id: 'teh', display: '__eh', answer: 't', choices: ['t', 'd', 'k'], image: '🍵' },
  { id: 'air', display: '__ir', answer: 'a', choices: ['a', 'i', 'e'], image: '💧' },
  // Additional 130 questions for Lengkapi Suku Kata Belakang
  { id: 'lari', display: '__ri', answer: 'la', choices: ['la', 'li', 'le'], image: '🏃' },
  { id: 'babi', display: '__bi', answer: 'ba', choices: ['ba', 'be', 'bo'], image: '🐖' },
  { id: 'cari', display: '__ri', answer: 'ca', choices: ['ca', 'ci', 'ce'], image: '🔍' },
  { id: 'duri', display: '__ri', answer: 'du', choices: ['du', 'di', 'de'], image: '🌵' },
  { id: 'foto', display: '__to', answer: 'fo', choices: ['fo', 'fa', 'fi'], image: '📷' },
  { id: 'guru', display: '__ru', answer: 'gu', choices: ['gu', 'ga', 'ge'], image: '👩‍🏫' },
  { id: 'hati', display: '__ti', answer: 'ha', choices: ['ha', 'hi', 'he'], image: '❤️' },
  { id: 'ikan', display: '__kan', answer: 'i', choices: ['i', 'e', 'a'], image: '🐟' },
  { id: 'jari', display: '__ri', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '👆' },
  { id: 'kota', display: '__ta', answer: 'ko', choices: ['ko', 'ka', 'ki'], image: '🏙️' },
  { id: 'lucu', display: '__cu', answer: 'lu', choices: ['lu', 'la', 'le'], image: '😄' },
  { id: 'meja', display: '__ja', answer: 'me', choices: ['me', 'ma', 'mi'], image: '🪑' },
  { id: 'nada', display: '__da', answer: 'na', choices: ['na', 'ni', 'ne'], image: '🎵' },
  { id: 'pagi', display: '__gi', answer: 'pa', choices: ['pa', 'pi', 'pe'], image: '🌅' },
  { id: 'rusa', display: '__sa', answer: 'ru', choices: ['ru', 'ra', 'ri'], image: '🦌' },
  { id: 'sapi', display: '__pi', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🐄' },
  { id: 'tangan', display: '__gan', answer: 'tan', choices: ['tan', 'tin', 'ten'], image: '✋' },
  { id: 'ular', display: '__lar', answer: 'u', choices: ['u', 'o', 'a'], image: '🐍' },
  { id: 'vas', display: '__as', answer: 'v', choices: ['v', 'f', 'w'], image: '🏺' },
  { id: 'wangi', display: '__gi', answer: 'wan', choices: ['wan', 'win', 'wen'], image: '🌸' },
  { id: 'bola', display: '__la', answer: 'bo', choices: ['bo', 'ba', 'bi'], image: '⚽' },
  { id: 'cinta', display: '__ta', answer: 'cin', choices: ['cin', 'can', 'cen'], image: '💕' },
  { id: 'dapur', display: '__pur', answer: 'da', choices: ['da', 'di', 'de'], image: '🍳' },
  { id: 'emas', display: '__mas', answer: 'e', choices: ['e', 'a', 'i'], image: '🏆' },
  { id: 'film', display: '__ilm', answer: 'f', choices: ['f', 'v', 'p'], image: '🎬' },
  { id: 'gula', display: '__la', answer: 'gu', choices: ['gu', 'ga', 'gi'], image: '🍯' },
  { id: 'hujan', display: '__jan', answer: 'hu', choices: ['hu', 'ha', 'hi'], image: '🌧️' },
  { id: 'jaket', display: '__ket', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '🧥' },
  { id: 'kamar', display: '__mar', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '🛏️' },
  { id: 'laptop', display: '__top', answer: 'lap', choices: ['lap', 'lip', 'lep'], image: '💻' },
  { id: 'mobil', display: '__bil', answer: 'mo', choices: ['mo', 'ma', 'mi'], image: '🚗' },
  { id: 'novel', display: '__vel', answer: 'no', choices: ['no', 'na', 'ni'], image: '📚' },
  { id: 'pantai', display: '__tai', answer: 'pan', choices: ['pan', 'pin', 'pen'], image: '🏖️' },
  { id: 'rumah', display: '__mah', answer: 'ru', choices: ['ru', 'ra', 'ri'], image: '🏠' },
  { id: 'sepatu', display: '__patu', answer: 'se', choices: ['se', 'sa', 'si'], image: '👟' },
  { id: 'tas', display: '__as', answer: 't', choices: ['t', 'd', 'k'], image: '👜' },
  { id: 'uang', display: '__ang', answer: 'u', choices: ['u', 'o', 'a'], image: '💰' },
  { id: 'vitamin', display: '__tamin', answer: 'vi', choices: ['vi', 'va', 've'], image: '💊' },
  { id: 'warna', display: '__rna', answer: 'wa', choices: ['wa', 'wi', 'we'], image: '🎨' },
  { id: 'xylophone', display: '__lophone', answer: 'xy', choices: ['xy', 'xa', 'xe'], image: '🎵' },
  { id: 'yacht', display: '__acht', answer: 'y', choices: ['y', 'i', 'e'], image: '⛵' },
  { id: 'zebra', display: '__bra', answer: 'ze', choices: ['ze', 'za', 'zi'], image: '🦓' },
  { id: 'apel', display: '__pel', answer: 'a', choices: ['a', 'i', 'e'], image: '🍎' },
  { id: 'bebek', display: '__bek', answer: 'be', choices: ['be', 'ba', 'bi'], image: '🦆' },
  { id: 'cerita', display: '__rita', answer: 'ce', choices: ['ce', 'ca', 'ci'], image: '📖' },
  { id: 'dolar', display: '__lar', answer: 'do', choices: ['do', 'da', 'di'], image: '💵' },
  { id: 'energi', display: '__nergi', answer: 'e', choices: ['e', 'a', 'i'], image: '⚡' },
  { id: 'flora', display: '__lora', answer: 'f', choices: ['f', 'v', 'p'], image: '🌸' },
  { id: 'gunung', display: '__nung', answer: 'gu', choices: ['gu', 'ga', 'gi'], image: '🏔️' },
  { id: 'harapan', display: '__rapan', answer: 'ha', choices: ['ha', 'hi', 'he'], image: '🌟' },
  { id: 'impor', display: '__mpor', answer: 'i', choices: ['i', 'e', 'a'], image: '📦' },
  { id: 'jakarta', display: '__karta', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '🏙️' },
  { id: 'kunci', display: '__nci', answer: 'ku', choices: ['ku', 'ka', 'ki'], image: '🔑' },
  { id: 'lemari', display: '__mari', answer: 'le', choices: ['le', 'la', 'li'], image: '🗄️' },
  { id: 'musik', display: '__sik', answer: 'mu', choices: ['mu', 'ma', 'mi'], image: '🎵' },
  { id: 'nangka', display: '__angka', answer: 'n', choices: ['n', 'm', 'l'], image: '🌴' },
  { id: 'pantun', display: '__antun', answer: 'p', choices: ['p', 'b', 'f'], image: '📜' },
  { id: 'radio', display: '__adio', answer: 'r', choices: ['r', 'l', 'n'], image: '📻' },
  { id: 'surat', display: '__rat', answer: 'su', choices: ['su', 'sa', 'si'], image: '✉️' },
  { id: 'taman', display: '__man', answer: 'ta', choices: ['ta', 'ti', 'te'], image: '🌳' },
  { id: 'udara', display: '__dara', answer: 'u', choices: ['u', 'o', 'a'], image: '💨' },
  { id: 'vas', display: '__as', answer: 'v', choices: ['v', 'f', 'w'], image: '🏺' },
  { id: 'wisata', display: '__sata', answer: 'wi', choices: ['wi', 'wa', 'we'], image: '🏖️' },
  { id: 'xenon', display: '__enon', answer: 'x', choices: ['x', 'z', 'c'], image: '⚛️' },
  { id: 'yogurt', display: '__ogurt', answer: 'y', choices: ['y', 'i', 'e'], image: '🥛' },
  { id: 'zaman', display: '__man', answer: 'za', choices: ['za', 'zi', 'ze'], image: '⏰' },
  { id: 'anggur', display: '__ggur', answer: 'an', choices: ['an', 'en', 'in'], image: '🍇' },
  { id: 'beras', display: '__ras', answer: 'be', choices: ['be', 'ba', 'bi'], image: '🌾' },
  { id: 'cerah', display: '__rah', answer: 'ce', choices: ['ce', 'ca', 'ci'], image: '☀️' },
  { id: 'dunia', display: '__nia', answer: 'du', choices: ['du', 'da', 'di'], image: '🌍' },
  { id: 'ekor', display: '__kor', answer: 'e', choices: ['e', 'a', 'i'], image: '🐒' },
  { id: 'fajar', display: '__jar', answer: 'fa', choices: ['fa', 'fi', 'fe'], image: '🌅' },
  { id: 'gajah', display: '__jah', answer: 'ga', choices: ['ga', 'gi', 'ge'], image: '🐘' },
  { id: 'hutan', display: '__tan', answer: 'hu', choices: ['hu', 'ha', 'hi'], image: '🌲' },
  { id: 'indah', display: '__dah', answer: 'in', choices: ['in', 'en', 'an'], image: '🌺' },
  { id: 'jagung', display: '__gung', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '🌽' },
  { id: 'kabar', display: '__bar', answer: 'ka', choices: ['ka', 'ki', 'ke'], image: '📰' },
  { id: 'laut', display: '__aut', answer: 'l', choices: ['l', 'r', 'n'], image: '🌊' },
  { id: 'matahari', display: '__tahari', answer: 'ma', choices: ['ma', 'mi', 'me'], image: '☀️' },
  { id: 'nanas', display: '__nas', answer: 'na', choices: ['na', 'ni', 'ne'], image: '🍍' },
  { id: 'pohon', display: '__hon', answer: 'po', choices: ['po', 'pa', 'pi'], image: '🌳' },
  { id: 'rantai', display: '__ntai', answer: 'ran', choices: ['ran', 'rin', 'ren'], image: '⛓️' },
  { id: 'sawah', display: '__wah', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🌾' },
  { id: 'tanah', display: '__nah', answer: 'ta', choices: ['ta', 'ti', 'te'], image: '🌱' },
  { id: 'ular', display: '__lar', answer: 'u', choices: ['u', 'o', 'a'], image: '🐍' },
  { id: 'vitamin', display: '__tamin', answer: 'vi', choices: ['vi', 'va', 've'], image: '💊' },
  { id: 'waktu', display: '__ktu', answer: 'wa', choices: ['wa', 'wi', 'we'], image: '⏰' },
  { id: 'xenophobia', display: '__nophobia', answer: 'xe', choices: ['xe', 'xa', 'xe'], image: '🌍' },
  { id: 'yakin', display: '__kin', answer: 'ya', choices: ['ya', 'yi', 'ye'], image: '💪' },
  { id: 'zona', display: '__ona', answer: 'z', choices: ['z', 's', 'c'], image: '🗺️' },
  { id: 'angin', display: '__gin', answer: 'an', choices: ['an', 'en', 'in'], image: '💨' },
  { id: 'bulan', display: '__lan', answer: 'bu', choices: ['bu', 'ba', 'bi'], image: '🌙' },
  { id: 'coklat', display: '__oklat', answer: 'c', choices: ['c', 's', 'k'], image: '🍫' },
  { id: 'darah', display: '__rah', answer: 'da', choices: ['da', 'di', 'de'], image: '🩸' },
  { id: 'es', display: '__es', answer: 'e', choices: ['e', 'a', 'i'], image: '🧊' },
  { id: 'foto', display: '__oto', answer: 'f', choices: ['f', 'v', 'p'], image: '📷' },
  { id: 'gunting', display: '__nting', answer: 'gun', choices: ['gun', 'gan', 'gin'], image: '✂️' },
  { id: 'hati', display: '__ati', answer: 'h', choices: ['h', 'g', 'l'], image: '❤️' },
  { id: 'ikan', display: '__ikan', answer: 'i', choices: ['i', 'e', 'a'], image: '🐟' },
  { id: 'jendela', display: '__ndela', answer: 'jen', choices: ['jen', 'jan', 'jin'], image: '🪟' },
  { id: 'kursi', display: '__rsi', answer: 'kur', choices: ['kur', 'kar', 'kir'], image: '🪑' },
  { id: 'lembaga', display: '__mbaga', answer: 'lem', choices: ['lem', 'lam', 'lim'], image: '🏛️' },
  { id: 'mobil', display: '__obil', answer: 'm', choices: ['m', 'n', 'b'], image: '🚗' },
  { id: 'novel', display: '__ovel', answer: 'n', choices: ['n', 'm', 'l'], image: '📖' },
  { id: 'pintu', display: '__ntu', answer: 'pin', choices: ['pin', 'pan', 'pen'], image: '🚪' },
  { id: 'rumput', display: '__mput', answer: 'rum', choices: ['rum', 'ram', 'rim'], image: '🌱' },
  { id: 'sekolah', display: '__kolah', answer: 'se', choices: ['se', 'sa', 'si'], image: '🏫' },
  { id: 'telepon', display: '__lepon', answer: 'te', choices: ['te', 'ta', 'ti'], image: '📞' },
  { id: 'universitas', display: '__versitas', answer: 'uni', choices: ['uni', 'una', 'une'], image: '🎓' },
  { id: 'vas', display: '__as', answer: 'v', choices: ['v', 'f', 'w'], image: '🏺' },
  { id: 'warung', display: '__rung', answer: 'wa', choices: ['wa', 'wi', 'we'], image: '🏪' },
  { id: 'xenon', display: '__enon', answer: 'x', choices: ['x', 'z', 'c'], image: '⚛️' },
  { id: 'yaitu', display: '__itu', answer: 'ya', choices: ['ya', 'yi', 'ye'], image: '📝' },
  { id: 'zakat', display: '__kat', answer: 'za', choices: ['za', 'zi', 'ze'], image: '🤲' }
];

const generateLengkapiSukuKataBelakangQuestions = (): Question[] => {
  return lengkapiSukuKataBelakangData.map(item => ({
    id: item.id + '_belakang',
    type: 'lengkapi_suku_kata_belakang' as const,
    prompt: 'Lengkapi bagian depan kata dengan suku kata yang tepat',
    display: item.display,
    ttsText: item.id,
    answer: item.answer,
    choices: shuffleArray(item.choices),
    image: item.image,
    word: item.id,
    level: 'mudah',
    tags: ['lengkapi_suku_kata_belakang']
  }));
};

// Lengkapi Suku Kata questions (150 questions) - from document
const lengkapiSukaKataData = [
  { id: 'sapu', display: 'sa__', answer: 'pu', choices: ['pu', 'pi', 'pa'], image: '🧹' },
  { id: 'buka', display: 'bu__', answer: 'ka', choices: ['ka', 'ku', 'ki'], image: '📖' },
  { id: 'topi', display: 'to__', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🎩' },
  { id: 'roda', display: 'ro__', answer: 'da', choices: ['da', 'di', 'du'], image: '🛞' },
  { id: 'baju', display: 'ba__', answer: 'ju', choices: ['ju', 'ja', 'jo'], image: '👕' },
  { id: 'mata', display: 'ma__', answer: 'ta', choices: ['ta', 'ti', 'tu'], image: '👁️' },
  { id: 'kaki', display: 'ka__', answer: 'ki', choices: ['ki', 'ka', 'ko'], image: '🦵' },
  { id: 'nasi', display: 'na__', answer: 'si', choices: ['si', 'sa', 'se'], image: '🍚' },
  { id: 'gigi', display: 'gi__', answer: 'gi', choices: ['gi', 'ga', 'go'], image: '🦷' },
  { id: 'dada', display: 'da__', answer: 'da', choices: ['da', 'di', 'de'], image: '🫁' },
  { id: 'mama', display: 'ma__', answer: 'ma', choices: ['ma', 'mi', 'me'], image: '👩' },
  { id: 'papa', display: 'pa__', answer: 'pa', choices: ['pa', 'pi', 'pe'], image: '👨' },
  { id: 'susu', display: 'su__', answer: 'su', choices: ['su', 'si', 'se'], image: '🥛' },
  { id: 'kuku', display: 'ku__', answer: 'ku', choices: ['ku', 'ka', 'ki'], image: '💅' },
  { id: 'lala', display: 'la__', answer: 'la', choices: ['la', 'li', 'le'], image: '🎵' },
  { id: 'tahu', display: 'ta__', answer: 'hu', choices: ['hu', 'ha', 'hi'], image: '🧈' },
  { id: 'soto', display: 'so__', answer: 'to', choices: ['to', 'ta', 'ti'], image: '🍲' },
  { id: 'kopi', display: 'ko__', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '☕' },
  { id: 'teh', display: 'te__', answer: 'h', choices: ['h', 'k', 't'], image: '🍵' },
  { id: 'air', display: 'a__', answer: 'ir', choices: ['ir', 'ar', 'er'], image: '💧' },
  // Additional 130 questions for Lengkapi Suku Kata Depan
  { id: 'lari', display: 'la__', answer: 'ri', choices: ['ri', 'ra', 're'], image: '🏃' },
  { id: 'babi', display: 'ba__', answer: 'bi', choices: ['bi', 'ba', 'be'], image: '🐖' },
  { id: 'cari', display: 'ca__', answer: 'ri', choices: ['ri', 'ra', 'ru'], image: '🔍' },
  { id: 'duri', display: 'du__', answer: 'ri', choices: ['ri', 'ra', 're'], image: '🌵' },
  { id: 'foto', display: 'fo__', answer: 'to', choices: ['to', 'ta', 'ti'], image: '📷' },
  { id: 'guru', display: 'gu__', answer: 'ru', choices: ['ru', 'ra', 're'], image: '👩‍🏫' },
  { id: 'hati', display: 'ha__', answer: 'ti', choices: ['ti', 'ta', 'te'], image: '❤️' },
  { id: 'ikan', display: 'i__', answer: 'kan', choices: ['kan', 'kin', 'ken'], image: '🐟' },
  { id: 'jari', display: 'ja__', answer: 'ri', choices: ['ri', 'ra', 're'], image: '👆' },
  { id: 'kota', display: 'ko__', answer: 'ta', choices: ['ta', 'ti', 'te'], image: '🏙️' },
  { id: 'lucu', display: 'lu__', answer: 'cu', choices: ['cu', 'ca', 'ci'], image: '😄' },
  { id: 'meja', display: 'me__', answer: 'ja', choices: ['ja', 'ji', 'je'], image: '🪑' },
  { id: 'nada', display: 'na__', answer: 'da', choices: ['da', 'di', 'de'], image: '🎵' },
  { id: 'pagi', display: 'pa__', answer: 'gi', choices: ['gi', 'ga', 'ge'], image: '🌅' },
  { id: 'rusa', display: 'ru__', answer: 'sa', choices: ['sa', 'si', 'se'], image: '🦌' },
  { id: 'sapi', display: 'sa__', answer: 'pi', choices: ['pi', 'pa', 'pe'], image: '🐄' },
  { id: 'tangan', display: 'tan__', answer: 'gan', choices: ['gan', 'gin', 'gen'], image: '✋' },
  { id: 'ular', display: 'u__', answer: 'lar', choices: ['lar', 'lir', 'ler'], image: '🐍' },
  { id: 'vas', display: 'v__', answer: 'as', choices: ['as', 'is', 'es'], image: '🏺' },
  { id: 'wangi', display: 'wan__', answer: 'gi', choices: ['gi', 'ga', 'ge'], image: '🌸' },
  { id: 'bola', display: 'bo__', answer: 'la', choices: ['la', 'li', 'le'], image: '⚽' },
  { id: 'cinta', display: 'cin__', answer: 'ta', choices: ['ta', 'ti', 'te'], image: '💕' },
  { id: 'dapur', display: 'da__', answer: 'pur', choices: ['pur', 'pir', 'per'], image: '🍳' },
  { id: 'emas', display: 'e__', answer: 'mas', choices: ['mas', 'mis', 'mes'], image: '🏆' },
  { id: 'film', display: 'f__', answer: 'ilm', choices: ['ilm', 'alm', 'elm'], image: '🎬' },
  { id: 'gula', display: 'gu__', answer: 'la', choices: ['la', 'li', 'le'], image: '🍯' },
  { id: 'hujan', display: 'hu__', answer: 'jan', choices: ['jan', 'jin', 'jen'], image: '🌧️' },
  { id: 'jaket', display: 'ja__', answer: 'ket', choices: ['ket', 'kit', 'kat'], image: '🧥' },
  { id: 'kamar', display: 'ka__', answer: 'mar', choices: ['mar', 'mir', 'mer'], image: '🛏️' },
  { id: 'laptop', display: 'lap__', answer: 'top', choices: ['top', 'tip', 'tap'], image: '💻' },
  { id: 'mobil', display: 'mo__', answer: 'bil', choices: ['bil', 'bal', 'bel'], image: '🚗' },
  { id: 'novel', display: 'no__', answer: 'vel', choices: ['vel', 'val', 'vil'], image: '📚' },
  { id: 'pantai', display: 'pan__', answer: 'tai', choices: ['tai', 'tii', 'tai'], image: '🏖️' },
  { id: 'rumah', display: 'ru__', answer: 'mah', choices: ['mah', 'mih', 'meh'], image: '🏠' },
  { id: 'sepatu', display: 'se__', answer: 'patu', choices: ['patu', 'pitu', 'petu'], image: '👟' },
  { id: 'tas', display: 't__', answer: 'as', choices: ['as', 'is', 'es'], image: '👜' },
  { id: 'uang', display: 'u__', answer: 'ang', choices: ['ang', 'ing', 'eng'], image: '💰' },
  { id: 'vitamin', display: 'vi__', answer: 'tamin', choices: ['tamin', 'timin', 'teman'], image: '💊' },
  { id: 'warna', display: 'wa__', answer: 'rna', choices: ['rna', 'rni', 'rne'], image: '🎨' },
  { id: 'xylophone', display: 'xy__', answer: 'lophone', choices: ['lophone', 'laphone', 'lophone'], image: '🎵' },
  { id: 'yacht', display: 'y__', answer: 'acht', choices: ['acht', 'icht', 'echt'], image: '⛵' },
  { id: 'zebra', display: 'ze__', answer: 'bra', choices: ['bra', 'bri', 'bre'], image: '🦓' },
  { id: 'apel', display: 'a__', answer: 'pel', choices: ['pel', 'pil', 'pal'], image: '🍎' },
  { id: 'bebek', display: 'be__', answer: 'bek', choices: ['bek', 'bak', 'bik'], image: '🦆' },
  { id: 'cerita', display: 'ce__', answer: 'rita', choices: ['rita', 'rita', 'reta'], image: '📖' },
  { id: 'dolar', display: 'do__', answer: 'lar', choices: ['lar', 'lir', 'ler'], image: '💵' },
  { id: 'energi', display: 'e__', answer: 'nergi', choices: ['nergi', 'nargi', 'nergi'], image: '⚡' },
  { id: 'flora', display: 'f__', answer: 'lora', choices: ['lora', 'lara', 'lira'], image: '🌸' },
  { id: 'gunung', display: 'gu__', answer: 'nung', choices: ['nung', 'nang', 'ning'], image: '🏔️' },
  { id: 'harapan', display: 'ha__', answer: 'rapan', choices: ['rapan', 'ripan', 'repan'], image: '🌟' },
  { id: 'impor', display: 'i__', answer: 'mpor', choices: ['mpor', 'mpar', 'mpir'], image: '📦' },
  { id: 'jakarta', display: 'ja__', answer: 'karta', choices: ['karta', 'kirta', 'kerta'], image: '🏙️' },
  { id: 'kunci', display: 'ku__', answer: 'nci', choices: ['nci', 'nca', 'nce'], image: '🔑' },
  { id: 'lemari', display: 'le__', answer: 'mari', choices: ['mari', 'miri', 'meri'], image: '🗄️' },
  { id: 'musik', display: 'mu__', answer: 'sik', choices: ['sik', 'sak', 'sik'], image: '🎵' },
  { id: 'nangka', display: 'n__', answer: 'angka', choices: ['angka', 'angka', 'angka'], image: '🌴' },
  { id: 'pantun', display: 'p__', answer: 'antun', choices: ['antun', 'antin', 'anten'], image: '📜' },
  { id: 'radio', display: 'r__', answer: 'adio', choices: ['adio', 'adia', 'idio'], image: '📻' },
  { id: 'surat', display: 'su__', answer: 'rat', choices: ['rat', 'rit', 'ret'], image: '✉️' },
  { id: 'taman', display: 'ta__', answer: 'man', choices: ['man', 'min', 'men'], image: '🌳' },
  { id: 'udara', display: 'u__', answer: 'dara', choices: ['dara', 'dira', 'dera'], image: '💨' },
  { id: 'vas', display: 'v__', answer: 'as', choices: ['as', 'is', 'es'], image: '🏺' },
  { id: 'wisata', display: 'wi__', answer: 'sata', choices: ['sata', 'sita', 'seta'], image: '🏖️' },
  { id: 'xenon', display: 'x__', answer: 'enon', choices: ['enon', 'enan', 'enin'], image: '⚛️' },
  { id: 'yogurt', display: 'y__', answer: 'ogurt', choices: ['ogurt', 'ogart', 'ogirt'], image: '🥛' },
  { id: 'zaman', display: 'za__', answer: 'man', choices: ['man', 'min', 'men'], image: '⏰' },
  { id: 'anggur', display: 'an__', answer: 'ggur', choices: ['ggur', 'ggar', 'ggir'], image: '🍇' },
  { id: 'beras', display: 'be__', answer: 'ras', choices: ['ras', 'ris', 'res'], image: '🌾' },
  { id: 'cerah', display: 'ce__', answer: 'rah', choices: ['rah', 'rih', 'reh'], image: '☀️' },
  { id: 'dunia', display: 'du__', answer: 'nia', choices: ['nia', 'nia', 'nea'], image: '🌍' },
  { id: 'ekor', display: 'e__', answer: 'kor', choices: ['kor', 'kar', 'kir'], image: '🐒' },
  { id: 'fajar', display: 'fa__', answer: 'jar', choices: ['jar', 'jir', 'jer'], image: '🌅' },
  { id: 'gajah', display: 'ga__', answer: 'jah', choices: ['jah', 'jih', 'jeh'], image: '🐘' },
  { id: 'hutan', display: 'hu__', answer: 'tan', choices: ['tan', 'tin', 'ten'], image: '🌲' },
  { id: 'indah', display: 'in__', answer: 'dah', choices: ['dah', 'dih', 'deh'], image: '🌺' },
  { id: 'jagung', display: 'ja__', answer: 'gung', choices: ['gung', 'gang', 'ging'], image: '🌽' },
  { id: 'kabar', display: 'ka__', answer: 'bar', choices: ['bar', 'bir', 'ber'], image: '📰' },
  { id: 'laut', display: 'l__', answer: 'aut', choices: ['aut', 'ait', 'eut'], image: '🌊' },
  { id: 'matahari', display: 'ma__', answer: 'tahari', choices: ['tahari', 'tihari', 'tahari'], image: '☀️' },
  { id: 'nanas', display: 'na__', answer: 'nas', choices: ['nas', 'nis', 'nes'], image: '🍍' },
  { id: 'pohon', display: 'po__', answer: 'hon', choices: ['hon', 'han', 'hin'], image: '🌳' },
  { id: 'rantai', display: 'ran__', answer: 'tai', choices: ['tai', 'tii', 'tai'], image: '⛓️' },
  { id: 'sawah', display: 'sa__', answer: 'wah', choices: ['wah', 'wih', 'weh'], image: '🌾' },
  { id: 'tanah', display: 'ta__', answer: 'nah', choices: ['nah', 'nih', 'neh'], image: '🌱' },
  { id: 'ular', display: 'u__', answer: 'lar', choices: ['lar', 'lir', 'ler'], image: '🐍' },
  { id: 'vitamin', display: 'vi__', answer: 'tamin', choices: ['tamin', 'timin', 'teman'], image: '💊' },
  { id: 'waktu', display: 'wa__', answer: 'ktu', choices: ['ktu', 'kti', 'kte'], image: '⏰' },
  { id: 'xenophobia', display: 'xe__', answer: 'nophobia', choices: ['nophobia', 'naphobia', 'nephobia'], image: '🌍' },
  { id: 'yakin', display: 'ya__', answer: 'kin', choices: ['kin', 'kan', 'ken'], image: '💪' },
  { id: 'zona', display: 'z__', answer: 'ona', choices: ['ona', 'oni', 'one'], image: '🗺️' },
  { id: 'angin', display: 'an__', answer: 'gin', choices: ['gin', 'gan', 'gen'], image: '💨' },
  { id: 'bulan', display: 'bu__', answer: 'lan', choices: ['lan', 'lin', 'len'], image: '🌙' },
  { id: 'coklat', display: 'c__', answer: 'oklat', choices: ['oklat', 'oklet', 'oklit'], image: '🍫' },
  { id: 'darah', display: 'da__', answer: 'rah', choices: ['rah', 'rih', 'reh'], image: '🩸' },
  { id: 'es', display: 'e__', answer: 'es', choices: ['es', 'as', 'is'], image: '🧊' },
  { id: 'foto', display: 'f__', answer: 'oto', choices: ['oto', 'ota', 'oti'], image: '📷' },
  { id: 'gunting', display: 'gun__', answer: 'ting', choices: ['ting', 'tang', 'ting'], image: '✂️' },
  { id: 'hati', display: 'h__', answer: 'ati', choices: ['ati', 'ata', 'eti'], image: '❤️' },
  { id: 'ikan', display: 'i__', answer: 'kan', choices: ['kan', 'kin', 'ken'], image: '🐟' },
  { id: 'jendela', display: 'jen__', answer: 'dela', choices: ['dela', 'dila', 'dela'], image: '🪟' },
  { id: 'kursi', display: 'kur__', answer: 'si', choices: ['si', 'sa', 'se'], image: '🪑' },
  { id: 'lembaga', display: 'lem__', answer: 'baga', choices: ['baga', 'biga', 'bega'], image: '🏛️' },
  { id: 'mobil', display: 'm__', answer: 'obil', choices: ['obil', 'obal', 'obel'], image: '🚗' },
  { id: 'novel', display: 'n__', answer: 'ovel', choices: ['ovel', 'oval', 'ovil'], image: '📖' },
  { id: 'pintu', display: 'pin__', answer: 'tu', choices: ['tu', 'ta', 'ti'], image: '🚪' },
  { id: 'rumput', display: 'rum__', answer: 'put', choices: ['put', 'pat', 'pit'], image: '🌱' },
  { id: 'sekolah', display: 'se__', answer: 'kolah', choices: ['kolah', 'kilah', 'kelah'], image: '🏫' },
  { id: 'telepon', display: 'te__', answer: 'lepon', choices: ['lepon', 'lapon', 'lipon'], image: '📞' },
  { id: 'universitas', display: 'u__', answer: 'niversitas', choices: ['niversitas', 'nversitas', 'nuversitas'], image: '🎓' },
  { id: 'vas', display: 'v__', answer: 'as', choices: ['as', 'is', 'es'], image: '🏺' },
  { id: 'warung', display: 'wa__', answer: 'rung', choices: ['rung', 'rang', 'ring'], image: '🏪' },
  { id: 'xenon', display: 'x__', answer: 'enon', choices: ['enon', 'enan', 'enin'], image: '⚛️' },
  { id: 'yaitu', display: 'ya__', answer: 'itu', choices: ['itu', 'ita', 'ite'], image: '📝' },
  { id: 'zakat', display: 'za__', answer: 'kat', choices: ['kat', 'kit', 'ket'], image: '🤲' }
];

const generateLengkapiSukaKataQuestions = (): Question[] => {
  return lengkapiSukaKataData.map(item => ({
    id: item.id,
    type: 'lengkapi_suku_kata' as const,
    prompt: 'Lengkapi kata dengan suku kata yang tepat',
    display: item.display,
    ttsText: item.id,
    answer: item.answer,
    choices: shuffleArray(item.choices),
    image: item.image,
    word: item.id,
    level: 'mudah',
    tags: ['lengkapi_suku_kata']
  }));
};

export const generateQuizQuestions = (
  quizType: string,
  count: number,
  seenIds: Set<string>
): Question[] => {
  let allQuestions: Question[] = [];
  
  switch (quizType) {
    case 'suku_kata':
      allQuestions = generateSukaKataQuestions();
      break;
    case 'awal_kata':
      allQuestions = generateAwalKataQuestions();
      break;
    case 'akhir_kata':
      allQuestions = generateAkhirKataQuestions();
      break;
    case 'tengah_kata':
      allQuestions = generateTengahKataQuestions();
      break;
    case 'lengkapi_suku_kata':
      allQuestions = generateLengkapiSukaKataQuestions();
      break;
    case 'lengkapi_suku_kata_belakang':
      allQuestions = generateLengkapiSukuKataBelakangQuestions();
      break;
  }
  
  // Filter out seen questions if remember setting is enabled
  const availableQuestions = allQuestions.filter(q => !seenIds.has(q.id));
  
  // If not enough unseen questions, use all questions
  const questionsToUse = availableQuestions.length >= count 
    ? availableQuestions 
    : allQuestions;
  
  // Shuffle and select requested count
  const shuffled = shuffleArray(questionsToUse);
  return shuffled.slice(0, count);
};
